### ISSUE TITLE
Design overall data processing flowchart

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#14]
The current proposed data processing flow chart is:

1) capture image with openCV
2) find finder patterns

Tests (go back to 1 if tests don't pass):
3) fast test exposure quality
4) fast test absence of shadows
5) fast test focus quality

When all tests pass:
6) perspective transform
7) extract calibration card patch colours
8) compute colour calibration matrix
9) Use calibration to compute corrected image

Test strip analysis:
10) find strip
11) extract colours in strip
12) compute result
13) store result

![flowchartv1](https://cloud.githubusercontent.com/assets/478954/8517160/c29dcd6e-23bd-11e5-9267-4618b01e02a3.png)

**Comment by ldporsius** [comment]
When would you say:
- exposure is ok?
- there are no shadows?
- preview is sharp enough?

**Comment by ldporsius** [comment]
I have adjusted my code according to this workflow now. First exposure check, then shadow check, then focus. But it is in the form of TODO's. Therefore I would very much appreciate any thoughts on how to set the treshold for those.

**Comment by mtwestra** [comment]
In light of our discussion yesterday, I think the order should be:

1) let the app adapt its focus and exposure without setting anything particular
2) try to find the finder patterns
3) when we first find the finder patterns, we optionally could add an extra step of sending the autofocus command. In that way, we use the 'finder patterns found' as the 'take a picture' button command
4) when we have the preview image, do the checks:
    a) exposure ok?
    b) no shadows?
    c) focus ok?

regarding the tresholds for the checks, I would experiment with different conditions, and then see what reasonable values are. 
As a first guess, you could use:

Exposure:
a) on all channels, less than 3% of pixels is in saturation (ie, either 0 or 255)
b) on all channels, the minimum value is below 15, and the maximum value is above 240

Shadows:
In the greyscale channel
1) determine the the average greyscale value of the white lines between the finder patterns 
2) for each pixel on those lines, the value should differ less than 5% of the average. Perhaps this is too strict, and then we can use 10%

Focus:
Here we need to experiment a bit more: see what the histogram of the laplace transform of the finder patterns looks like, what kind of maximum values it gives.
