### ISSUE TITLE
Remove OpenCV library dependency

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#158]

**Comment by janagombitova** [comment]
I am reopening this issue as Joy reported via support that the latest version of the app does not work without having OpenCV installed and we do not provide a warning to the user. 

From my understanding we removed the need to have to install OpenCV to be able to run Caddisfly tests and this should be something to aim for. 

@nhternup can you check what is happening?

**Comment by janagombitova** [comment]
Reply from @nhternup: 
Date: 6 September 2018 at 14:39:17 GMT+2

The latest version of Caddisfly (1.0.0.1) on Play store should not require OpenCV. It was tested without OpenCV. 

When you get a chance could you please uninstall OpenCV and check if it affects the tests. Maybe it was a coincidence and something else like low light condition was affecting it instead. Thanks

# Next steps 
Mert and me will test out and confirm

**Comment by janagombitova** [comment]
Tested and confirmed all works well and the dependency is no longer needed to run the tests
