### ISSUE TITLE
Fix focus issue on Samsung Galaxy J6

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#163]
Users have reported an issue on the Samsung Galaxy J6, where the camera doesn't focus when the measurement is done. This leads to an inability to complete the measurement. I have seen this behaviour on the device of the user.

I will try to replicate this behaviour on a Samsung Galaxy J6 I have acquired, and will post the results and possible handling here.

**Comment by nhternup** [comment]
Duplicate. Fixed in #168
