### ISSUE TITLE
User interface design

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#17]
What are we going to show the user? 

From max to min:
- the original image taken,
- the result of the calibration, 
- the strip test after adjusting with calibration outcome,
- the result of what values for ppm are derived.

We haven't discussed this as yet, but I think some of the code now already might depend on decisions we make here. For instance, if we want to show the strip to the user as 'cut out' from the rest, we could do that in the preview stage and save it as a separate image. If we only want to present the results, we can skip that.

And anyhow, eventually we need to discuss how this is going to be part of the Caddisfly UI.

**Comment by mtwestra** [comment]
Yes, we need to think about this. I think the Caddisfly team will have some good ideas about this - perhaps you can discuss it with Sam?

**Comment by mtwestra** [comment]
A first attempt at a workflow: 
We need to discuss this with @aadvaark, @loicsans, @Kiarii.
![workflow](https://cloud.githubusercontent.com/assets/478954/9525710/bbdd9f3a-4ce5-11e5-9f99-a09912b24a77.png)

**Comment by mtwestra** [comment]
A first list of functional requirements:
- From within the caddisfly app, the user should be able to choose which test she wants to do
- It should be easy for the user to check if she is using the right strip with the right test
- When the user has selected the test, any information on how to perform the test should be available in the app
- Some strip patches need to be read out after certain time intervals. The UI should make clear what the app is doing.
- When the app is looking for a good picture, it should give feedback as to the quality of the lighting, absence of shadows, focus, etc.
- When the results are displayed, it should be easy to check if the results make sense, i.e., if the patches are found in the right location, and if the colour has been interpreted correctly.
- The app should send back the data of the measurement, together with the image the data was based on, so quality checks can be done later.
- The UI should work for strip tests with a large number of patches, say, 10.

Question:
- should the app display the colour scale the measurement is based on? This might be possible for one or two patches, but will be difficult for many.

**Comment by ldporsius** [comment]
The functional requirements are aiming high, and so they should. But for now, just focusing on the ideas of the proposed workflow, I think that it shows two things, namely: the importance to guide the user by means of clear instructions and the benefit of an overview in which state of the process from beginning to start the user finds herself.
So I thought about that and then I thought: we could elaborate a bit upon that idea and present to the user a list of steps to take, together with clear instructions for each step.

So first we show a list of instructions:

![device-2015-09-05-193201](https://cloud.githubusercontent.com/assets/9623423/9700572/c79bda0c-5407-11e5-98aa-af04917fe351.png)

When more information is needed, user can click the instruction, and gets to see this:

First instruction:

![device-2015-09-05-192201](https://cloud.githubusercontent.com/assets/9623423/9700576/00c8ba48-5408-11e5-8eab-6bf30113f2cd.png)

Second instruction:

![device-2015-09-05-192138](https://cloud.githubusercontent.com/assets/9623423/9700577/102cb610-5408-11e5-81ab-75a7e9ccc422.png)

**Comment by ldporsius** [comment]
Just an idea. Not to worry, this is just on a side-line, no need to alter existing code. With the help of Android Studio Widgets you can do this within the hour. A kind of mockups by lack of a mockup tool.

**Comment by ldporsius** [comment]
Worked it out some more:

![device-2015-09-06-165925](https://cloud.githubusercontent.com/assets/9623423/9705066/af90c3ee-54b8-11e5-9aff-b8935634a30b.png)

**Comment by ldporsius** [comment]
@mtwestra In the functional requirements it says:

"When the app is looking for a good picture, it should give feedback as to the quality of the lighting, absence of shadows, focus, etc."

Now here is a technical problem. As up to yesterday, we handled all of this processes inside the Camera.PreviewCallback. But a major issue was, that the quality of the preview data seems to be to poor: we got weird colored pixels here and there and had no explanation for it besides that we needed more bytes. Today I worked from that idea and altered the code as follows: When finder patterns are found, take a picture (camera.takePicture()) and send the byte[] that results to the next Activity. So that we have more reliable data as to color to go upon. 
I just think it will cost a lot of overhead, if we do this inside the PreviewCallback, just to do the quality check. That will mean that every ? second we must convert the preview into a byte[] array with takePicture, convert that into a bitmap or Mat object, to do the checks. 

Summarizing: We could test if indeed the overhead is a problem, but otherwise either we stick with the preview byte[], or we postpone the quality checks until a picture is taken.

**Comment by mtwestra** [comment]
closing this for now

**Comment by mtwestra** [comment]
Because we needed to go to portrait mode, here is a new attempt at workflow:
[mainScreen.pdf](https://github.com/akvo/akvo-caddisfly/files/27887/mainScreen.pdf)

**Comment by ldporsius** [comment]
Could you please elaborate some about the shadow indicator? What is the meaning of the red and green bars when it comes to shadows? As for the brightness, it seems clear to me, that it is an indication of the percentage of light, that when a certain limit is reached, changes color. But with shadows, what does it mean? 6 red bars: we have 60% shadows, 2 green bars: but now we have 20% without? I do not understand this, doesn't seem logical somehow.
