### ISSUE TITLE
Embed code in calibration card design

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#19]
We will have different calibration cards, for example different printed batches, which look very much the same. Therefore, we need a way for the device to know which calibration card is being used. 

The easiest way to accomplish this is to embed a computer-readable code in the calibration card. As we already use QR code finder patterns, it is natural to use a code that is based on this.

As a first attempt, we will use this design:

<img width="368" alt="screen shot 2015-09-14 at 16 39 48" src="https://cloud.githubusercontent.com/assets/478954/9852562/4192f2fc-5aff-11e5-9c8c-661551bde6fc.png">

We see the bottom-left finder pattern, a digital code, and a figure. (in this image, the code and the figure don't correspond). The black area at the top is part of the black area where the strip is placed on.

Vertically, the code is placed flush with the top side of the bottom-left finder pattern. Horizontally, the code is placed one module size to the left of the finder pattern, to respect the rule of 'empty space' which is obligatory around finder patterns.

The code has a length of 12 bits, and starts and ends with a 1 bit. Therefore, there are 10 bits that carry information. Those bits are interpreted as unsigned bits, with the least significant bit on the right. Each bit has a size of one module.

**Comment by mtwestra** [comment]
We will use the design below:
<img width="568" alt="screen shot 2015-10-02 at 14 45 07" src="https://cloud.githubusercontent.com/assets/478954/10246737/355ff836-6914-11e5-96db-7f0d15e19f30.png">
(the black bar at the top is just a part of the large black area on which the strip is placed)

1) we use a simple barcode style design, so it is easy to find
2) the height of the barcode is the same as the height of the finder pattern
3) The pattern starts at a distance of 2 modules of the right of the finder pattern
4) one bar is one module wide. Black means a 1.
5) There are 12 bars. Their role is:
bar 1: start bar, always black
bar 2..10: code bits
bar 11: parity bit 
bar 12: stop bar: always 1.

The code simply finds the pattern by:
1) drawing a line from the bottom left finder pattern to the bottom right one
2) estimate the location of the pattern
3) resample the pattern, and determine the bar width by dividing by 12
4) interpret the bits.

the depicted code is 1: 000000001
Embedded within start and stop bits, and a parity bit, this becomes 100000000111

**Comment by ldporsius** [comment]
We could change the filename in the assets folder to calibration + versionNumber + .json.
So for version 1 this becomes: "calibration1.json".

**Comment by ldporsius** [comment]
The code doesn't work. Probably because of the change from landscape to portrait view for the Camera.

**Comment by mtwestra** [comment]
yes. we need to fix the points used for the code computation.

**Comment by ldporsius** [comment]
I have moved the code from the FinderPattern Class to the CalibrationCard Class. I feel that makes more sense, because ultimately the barcode has nothing to do with finder patterns but everything with calibration data. Plus, in that way, the version number can be a static together with the calib. data object and can change only if the camera reads another version number (other card). And, most importantly, the version number is available in the DetectStripActivity because it is a static, where we need it to do the actual calibrating and cannot read it from the card (because camera is no longer there).
I hope you agree.

**Comment by mtwestra** [comment]
I put it in finderpattern class so the black and white image data that was created within the finder pattern class is still available. It is an expensive operation, and it doesn’t make sense to do it twice. So if it can still access that data, ok, otherwise, I would probably put it back.

**Comment by ldporsius** [comment]
The method you made it a part of, returns an object with the finder patterns. The BitMatrix that is needed in the method is available in the MyPreviewCallback class. So yes, that data is accessible from where the finderpattern find method is called, namely in MyPreviewCallback. It is not doing it twice, just once, but from different locations, if that makes any sense.

**Comment by mtwestra** [comment]
Excellent, then it is ok

**Comment by ldporsius** [comment]
The important part is, that we really need to store it as a static, because we need the version number in a completely separate Activity, where we do the calibration.
I understand that you would prefer to put it right at the very basis of where the finder patterns are found, because it is now so very linked to them, but then again: we need to unlink them, because we need the version number apart from the finder patterns later on.

**Comment by mtwestra** [comment]
yes, that is fine

**Comment by ldporsius** [comment]
Before setting the value of the property holding the version number, we should validate it. We can do the following:
- keep track of the readings and take the value that is most often.
- compare that value with predefined valid version numbers.

**Comment by ldporsius** [comment]
I put the version numbers that are read in a HashMap; it is more compact I think than putting them in a long (Array)List. Like this: Map<int versionNumber, int frequency>.

We simply look at the entry with the highest frequency: that's the one with the key we want.

Now theoretically it is possible that different versionNumbers have the same frequency. We can only pick one. Which one? 
I choose to pick the first. Would that work or does anyone see a problem beforehand?

**Comment by mtwestra** [comment]
sounds good to me
