### ISSUE TITLE
Stop supporting stand alone testing

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#191]
# Context 
Currently, anyone who downloads the Caddisfly app and buys Lovibond hardware or CBT bags themselves can use the Caddisfly app for stand-alone testing, without the connection to Akvo Flow. However, Akvo's strategy is to provide a full data solution, thus we do not offer Akvo Caddisfly as a stand alone product, only in the combination to Akvo Flow. 

# Opportunity or Problem to address 
The current implementation allows Alphonso to run a test that is supported by the Caddisfly app, see the result and document the result in a different tool (if wanted). We should review the workflow to see **how might we ensure Aplhonso cannot run a Caddisfly test is the data does not go back into Flow**. 

## To consider: 
- how and when to inform Aplhonso about the needed connection with Flow. 
- how to change the current workflow 
- what to show when opening the app directly (not via the Flow form)

**Comment by janagombitova** [comment]
In today's standup we agree that @nhternup will create a 1st iteration prototype where he will: 
- add intro page showing that you need Flow to be able to use Caddisfly for testing 
- remove the initial menu page with all the existing tests 

In the prototype we will check whether other changes are still needed to resolve the problem in Alphonso's workflow and if the initial screen is informative enough. We also need to make sure testing via Flow is still possible. 

@nhternup I just realised that by removing the initial menu with the button we not only loose the option to select the app language (what you said is taken from the Flow app - so that is not an issue), but we also loose the About page. Can you consider a different way to keep this settings that Alphonso can access?

**Comment by nhternup** [comment]
Couple of options to consider here:

**Option 1: With launcher Icon:**
If the Akvo Caddisfly launcher icon is clicked then something like the below screen shows up (message and design can be changed). Note that the settings menu icon has been replaced with an info icon which opens the about screen directly.
**Pro:** Can check if Akvo Caddisfly is installed by looking for the icon
**Con:** Confusion as to why another orange icon exists when it does nothing

![launch](https://user-images.githubusercontent.com/4124856/42563084-fb8577f0-851a-11e8-8d50-df2c04f04c49.png)

**Option 2: Without launcher icon**
The Akvo Caddisfly launcher icon is hidden on the device and only Akvo Flow icon is available and there is no way to directly open Akvo Caddisfly. In this case the about icon is moved to the first screen that appears after clicking the 'Go To Test' button on  a Caddisfly question in the survey form.
**Pro:** No confusion as there is only one icon to use every time
**Con:** Starting a test is the way to check if Akvo Caddisfly is installed

![test](https://user-images.githubusercontent.com/4124856/42563124-15c90cc6-851b-11e8-82c0-c35d4090cc8a.png)

**Comment by janagombitova** [comment]
@nhternup great alternatives and thank you for the detailed description. 

I would go for option 1 with implementing having the info icon available at the initial test screen as well because in case you only open Caddisfly from Flow, you still have the possibility to see the About page.

I prefer option one because usually once you install a new app from the Play Store you go to it and open it to check if the installation went ok and if the app worked. If we hide the launcher icon, the user might wonder if she did indeed successfully install the app. In the Play store she will see she has it, but not on her phone, thus being confused. With option 1 you can confirm the installation and also directly see that you need another app to proceed further. 

I am talking with Georgia (Comms team) today and will ask her what the best copy would be for the 1st page and share here.

**Comment by janagombitova** [comment]
@nhternup how about we add two intro/walkthrough screens: one introducing Akvo Caddisfly (marketing) and the second one to explain the Flow connection. We used this approach also for Flow app: https://github.com/akvo/akvo-flow-mobile/issues/984#issuecomment-380842217

What do you say? 

# Ideas: 

## Screen one
**Title:** Akvo Caddisfly 

**Text:** A water quality testing testing kit, on your smartphone. Test parameters as pH, E.coli, free chlorine and many more with the connected colorimetry, microbiology, sensor and strip tests. For more details check our user guide. 

**Button:** Next 

## Screen two 

**Title:** Connect with Akvo Flow

**Text:** Akvo Caddisfly is integrated with Akvo Flow, our mobile data collection tool. To conduct your water quality test, go to the Akvo Flow app and select the Caddisfly question defined in your survey form.

**Button:** Go to Akvo Flow
- If Flow is installed, open it
- If Flow is not installed should we show a message explaining you need to install the Flow app from your instance?

**Comment by nhternup** [comment]
@janagombitova good idea. Below are the screenshots with this change. 

**Notes:** 
1. an info icon added to top right corner to navigate to about page.
2. layout design taken from Akvo Flow walkthrough pages. Lock and Key icons to be changed
3. 'Flow Not found' message to be reworded as required

![step1](https://user-images.githubusercontent.com/4124856/42802985-2c85c944-89c2-11e8-9247-1eab7014a391.png)  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  ![step2](https://user-images.githubusercontent.com/4124856/42802986-2cc961cc-89c2-11e8-8127-319eaf0b74c7.png)

![notfound](https://user-images.githubusercontent.com/4124856/42802983-2c52d3d6-89c2-11e8-8cac-2fede4dd87fc.png)

**Comment by janagombitova** [comment]
@nhternup you are amazing! If you feel the design needs improvements to match the Caddisfly app's current design, please go ahead. What icons would you suggest instead of the lock and the key?

**Comment by nhternup** [comment]
Possible Icon suggestions:
Step 1: Maybe something related to water...a droplet?... (even though soil tests also exist).
Step 2: Maybe a survey form? to depict Akvo Flow...

**Comment by janagombitova** [comment]
Sounds good. Do you want to give it a shot?

**Comment by nhternup** [comment]
found droplet and clipboard icons

![step1-1](https://user-images.githubusercontent.com/4124856/42873553-e9100fea-8a9c-11e8-84c7-2b81ae423663.png) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![step2-1](https://user-images.githubusercontent.com/4124856/42873554-e93f5ce6-8a9c-11e8-9ae3-39e476fe226a.png)

**Comment by janagombitova** [comment]
@nhternup This is a great start! From the Akvo Caddisfly screen can you remove the last sentence: "For more...". With the little info icon, I think this is a bit redundant. On the Flow screen can you add a space (paragraph) before the "To conduct.." to break the text a bit and make it more readable?

**Comment by nhternup** [comment]
Changes made. Also added para space on first screen to keep it consistent

![step1-2](https://user-images.githubusercontent.com/4124856/42876970-e3c3cd34-8aa5-11e8-9c3d-5e5842ae40c1.png) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![step2-2](https://user-images.githubusercontent.com/4124856/42876972-e40c71f6-8aa5-11e8-9455-571f0d7525e2.png)

**Comment by janagombitova** [comment]
@nhternup sorry for one more revision. I ran the screens by @Kiarii who suggested to simplify the copy a bit more as the details should be available to the user on Play Store (still waiting for the revision from Arthur and Mert on this one) or via training on the apps. 

Here is the change from the copy below the images: 

Screen 1:
A water quality testing solution supporting over 20 parameters, like pH, E.coli or free chlorine. 

Test water quality using connected colorimetry, microbiology, sensor and strip tests. 

Screen 2:
Akvo Caddisfly is integrated with Akvo Flow, a data collection and monitoring tool. 

To conduct a water quality test go to Flow add select the Caddisfly question.

**Comment by nhternup** [comment]
Changes made:

![step1-3](https://user-images.githubusercontent.com/4124856/42886608-98fd79d2-8ac1-11e8-8770-399f9769a3b2.png)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![step2-3](https://user-images.githubusercontent.com/4124856/42886610-99369b36-8ac1-11e8-8ec5-e4b5dddd03e8.png)

**Comment by janagombitova** [comment]
Perfect!
