### ISSUE TITLE
On Play Store still marked as Unreleased

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#192]
# Context 

When searching for the Caddisfly app on Play Store it shows as Unreleased. 

![screenshot_2018-06-25-17-21-34](https://user-images.githubusercontent.com/12456965/41859492-91e91cfa-789c-11e8-818b-de18329a37e3.png)

# Change 
This is not the case anymore and we should change the settings in Google Play.

**Comment by arthurakvo** [comment]
One extra question: if Flow and Caddisfly are only to be used together, why should they be downloaded in two different places? So maybe it's a good idea to both install Flow and Caddislfly through the Playstore or download both from an instance. What do you think?

**Comment by janagombitova** [comment]
Ideally we want Flow app on Play Store but that is a larger change of its own. It is good Caddisfly is on Play Store and we should keep it there. In the description we state it's integration with Flow app. So that is also covered. But we need to change the unreleased part as that is outdated

**Comment by janagombitova** [comment]
In today's stand up we have agreed to officially release the Caddisfly app on Play Store. The app has not been officially released till now because we still had the option to perform a test without the Flow app, we were worried about the uptake on support and the possible negative reviews that could come because you cannot test without Flow what could be confusing to Play Store users not familiar with Akvo and the solution we provide.  

We have decided to release the app a address these concerns by: 
* [ ] reviewing copy and images currently on Play Store first to ensure it is clearly stated the need of Flow and the images are up to date and descriptive 
* [ ] once we are aware of the scope with MarComs provide new copy and images 
* [ ] implement the 1st iteration of not allowing to test without Flow https://github.com/akvo/akvo-caddisfly/issues/191
* [ ] publishing
