### ISSUE TITLE
Add new test: Chlorine and pH tester

### ISSUE THREAD

**Issue by MBlommestijn** [ternup/caddisfly-app#194]
The Lovibond pooltester measures pH and Residual Chlorine more accurate than the strip tests we have tested. The test method is used by the WHO and is cheap and easy to use. An extra benefit is that these two parameters automatically are measured together. Free chlorine can disinfect when the pH falls in a certain range. See the manual: https://www.lovibond.com/assets/Wasseranalytik/Instruction_Manuals/Schnelltests/Pooltester/00385290_pooltester_chlor_ph_multi_lovi.pdf

**Comment by janagombitova** [comment]
# Steps users take 

Here is the user workflow we envision for the new tests (work name Pooltester).  

1. Alphonso gets to the Caddisfly question in the Flow app and the app opens the test in Caddisfly app 
2. See's he is in the test with the picture of Pooltester and hits Next 
3. Sees the test interface on performing the test with Pooltester 
4. Performs the test 
5. Alphonso fills in the interface on the phone 
   - he sees a short intro text on what he needs to do
   - he sees the two colour + value columns of the Pooltester where the values are clickable 
   - he hits the result he sees on the tester in the app screen, this should somehow visually show him what he has selected 
   - he should have the option to change his mind - selects a different value
6. He has to select values for both columns
   - he needs to know that the test is only completed when he selects both values 
   - he can only select one value per column 
6. He sees a confirmation screen (message, something) to accept the result to confirm this is the final (not changeable) option
7. Alphonso is brought back to Flow 

# Next step 
* [ ] Arthur and Mart will provide @nhternup with visuals and details 
* [ ] Nischal will create the 1st iteration prototype to test the test ;); the new user workflow and experience

**Comment by nhternup** [comment]
@MertBlommestijn,  The user needs to scroll to view images for the last instruction step. Should we break that into 2 steps or is scrolling ok?

![instruction7](https://user-images.githubusercontent.com/4124856/42933015-644a3d9c-8b61-11e8-8c4c-e91d4d3d1f10.png)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;![instruction6](https://user-images.githubusercontent.com/4124856/42933174-be6ac760-8b61-11e8-96b9-ec321b720e62.png)

**Comment by MBlommestijn** [comment]
@nhternup You can leave out the top image (pt_6_result). So only show the interface (pt_7_interface).
