### ISSUE TITLE
Make apk available to install offline 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#195]
# Context 
Many of our users work in remote areas where connection is unreliable or not available. To run water quality tests with Caddisfly they, however, need to install the app from Google Play store what requires internet connection. 

# Opportunity 
The idea is to consider if we can have the apk also available somewhere to download so it can put installed directly on enumerators' devices. Besides thinking of where the apk should exists we should also consider the benefits and setbacks as well as other alternatives to solving the current problem users have.

**Comment by nhternup** [comment]
FYI 
It seems that with a Google approved file sharing app like '[Files by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files)' any Play store installed app can be shared offline and auto updates will work. Other approved apps are SHAREIt and Xender. 

Prerequisite: The sharing app should be installed beforehand.

Blog: https://android-developers.googleblog.com/2018/10/offline-p2p-installs-beta.html

**Comment by janagombitova** [comment]
Brilliant news. Adding an article to support about this and closing the issue
