### ISSUE TITLE
Dissolved oxygen (DO) 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#199]
We are considering to add another testing method for **dissolved oxygen**. 

# Why 

We have MD610 but it does not meet the needed high range. So we are considering for ecological water quality another testing method and device of Vernier, including Bluetooth connectivity.

https://www.vernier.com/products/sensors/dissolved-oxygen-probes/gdx-odo/

# Next steps 
* Testing internally to see the potential value
* Contact hardware provider to see if they are interested in a collaboration 
* Explore other tools out there

**Comment by janagombitova** [comment]
Mert created an overview of possible tests we can add to support testing DO. https://docs.google.com/document/d/13Y0jw7ckZitE8lgcSuk-CyvcO_vW6KaEtaOnB1HOtQs/edit

The next steps were to check if Vernier would be interested in connecting with us and to see how we could possibly incorporate one of Tintometer’s tests

**Comment by janagombitova** [comment]
After contacting Vernier we got the confirmation that they only focus on the educational use of their probes a thus cannot be used in our situation. Thus we will continue to investigate: 

* Tintometer - whether the MD610 photometer would work with a reagent for higher ranges covering at least 5mg/l O2 (Currently, the MD610 photometer would only be suitable for a very low range 0.01-0.8 mg/l. Since <5 mg/l in lakes and rivers is already unhealthy for aquatic life it should cover at least the 5 mg/l.)
* Tintometer - SD 400 Oxi L (Optical testing luminescence technology.)
* Palintest

**Comment by janagombitova** [comment]
Today we spoke with Mert on next steps: 
* Ask for manual for Vacu test from Tintometer to add as a "lower end" test 
* Ask our known experts (TU Delf) for advice on "high end" tests (Tintometer, Palintest, Hach)

**Comment by janagombitova** [comment]
Next steps: 
* [ ] Add support for OXI 400 Dissolved Oxygen sensor test (a short and long version). 
* [ ] Wait for manuals to add DO vacu vials as a reagent for the MD610 photometer (#258)

**Comment by janagombitova** [comment]
This issue is to add a new test: OXI 400 Dissolved Oxygen sensor test (Mert to provide all details). The user workflow is 'manual': go through instructions, take photo of screen with result, type in result field in the app, submit.

**Comment by valllllll2000** [comment]
<img src="https://user-images.githubusercontent.com/923280/93194554-82a85f80-f748-11ea-9b87-7c44bbc9a746.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194558-8340f600-f748-11ea-8ae6-95f740d8aa11.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194561-83d98c80-f748-11ea-9e4d-4f30cddf219a.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194562-83d98c80-f748-11ea-8033-381eb9e1f713.png" width="200" />

<img src="https://user-images.githubusercontent.com/923280/93194564-84722300-f748-11ea-81a1-ba24cc79e740.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194568-84722300-f748-11ea-8672-475da1108229.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194571-850ab980-f748-11ea-8f9c-26eb2fc57020.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93195464-930d0a00-f749-11ea-9ea7-763cbac7af27.png" width="200" />

<img src="https://user-images.githubusercontent.com/923280/93195465-943e3700-f749-11ea-8ef1-3acd1e21ac02.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194573-85a35000-f748-11ea-9db6-ebcccb95fec4.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93194575-85a35000-f748-11ea-8308-afe50ff1dac8.png" width="200" />

**Comment by janagombitova** [comment]
Mert and Valeria here are some comments: 
* point 2 is super hard to understand. Do we have an image to make that point more clear? Can we split the sentences? 
* point 3 - `wait until the display is initialised` - can this be removed? Isn't it sufficient to say, turn the device on? How else would I know the thing is on if the display is not on? 
* point 4 is also quite technical - Can we simplify it? `Immerse the sensor in the water sample. Make sure that the temperature sensor is fully immersed. Wait a bit till you take the measurement to ensure the dissolved oxygen is fully diffused.` Do we have an image to add to this step? 
* I would combine points 7 and 8 as those are no longer related to the measurement but storing and safe keeping. 
* What is the point on point 7? Can we make these storage instructions shorter and a bit more "human" in the sense of more actionable (do this, then do that, then that)?

**Comment by valllllll2000** [comment]
Updated screenshots:

<img src="https://user-images.githubusercontent.com/923280/93362333-26c40080-f846-11ea-9503-63ef7c4a7edf.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93362196-fda37000-f845-11ea-83f7-4e7619b2ff7a.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93362438-422f0b80-f846-11ea-915c-7c0c854be24a.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93362589-71457d00-f846-11ea-8628-096371c53a04.png" width="200" />

<img src="https://user-images.githubusercontent.com/923280/93362729-a05bee80-f846-11ea-8e67-5b97b415b052.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93362803-bff31700-f846-11ea-93cd-f86fbc9c9212.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93362892-d7320480-f846-11ea-84fd-16433a2c6602.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/93439925-6c78db80-f8cf-11ea-9fc1-54f6682c7980.png" width="200" />

<img src="https://user-images.githubusercontent.com/923280/93363131-1fe9bd80-f847-11ea-8e80-b5df2aced308.png" width="200" />
