### ISSUE TITLE
Error message + varying number of tests

### ISSUE THREAD

**Issue by saurabhlevin** [ternup/caddisfly-app#2]
We've observed that in the following phones (following update 0.61):
Moto G 1st gen
Samsung Duos 2
Samsung Duos 3 
Samsung Grand Prime
The phone takes up to 11 images (instead of the usual 6), and reports an error at the end of the test. Turning off the shake during test option with version 0.61 seemed to have temporarily solved the issue for the Moto G, but hasn't changed the behaviour of the Samsungs.

Edit: It doesn't seem to have fixed the issue for the Moto G. The test seems to work normally on the Asus which also runs 0.61.

**Comment by aadvaark** [comment]
Anything to do with the phone OS?

**Comment by aadvaark** [comment]
It's something to do with DeveloperMode. Phones behave when not in DeveloperMode.

**Comment by aadvaark** [comment]
Seems to be fixed. Certainly not happening now.
