### ISSUE TITLE
OpenCV and GooglePlay

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#20]
If we use OpenCV as a static library, no GooglePlayStore is required and hence no internet connection.
But then the app size is increased significantly (16 MB) because we have to include all the libraries that are otherwise downloaded.
So our option are:
- Download packages needed from GooglePlayStore
- Include them in the app

Could it cause problems on devices that do not have GooglePlayStore? Do we support devices that do not? Could we ask users to install it?

**Comment by mtwestra** [comment]
I thought you had managed to include a subset of openCV, so that it becomes much smaller?

**Comment by ldporsius** [comment]
That's another thing, the subset. I mean the download of OpenCVManager, that takes care of the .so libraries needed for a particular device: x86, armeabi, etc. 
If e.g. you take a look at OpenCV-android-sdk/sdk/native/libs/arm64-v8a, at the libopencv_java3.so file, you'll find that it is 14.2 MB. 
Now we can make those .so files part of the app, by copying them into app/java/libs (or jniLibs) or we can use the Async callback part of OpenCV to install them from GooglePlay. That's as far as I understand it.

**Comment by mtwestra** [comment]
One question to answer is how much OpenCV stuff we actually use, and if there might be alternatives for it - in case we need to reduce the size. Perhaps you can make a small list of our current usage in terms of image transforms, etc, and where we use them?

**Comment by mtwestra** [comment]
oh! I see - I am starting to understand how it works - the app downloads the native files for the specific device. So that means that there probably is no way around the size...

mark

**Comment by ldporsius** [comment]
The openCVManager app is 9.8 MB after download. Our app is 5.4MB after installation. If I make an apk the size is 3.5 MB.

**Comment by ldporsius** [comment]
I will make a list of usage of openCV.

**Comment by ldporsius** [comment]
Closing.
