### ISSUE TITLE
Improve structure of test names 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#204]
# Context 

One of the improvements we want to make to strengthen the Flow - Lumen - Caddisfly experience is to simplify how Salim selects his test when creating the Flow form. Currently the list of tests is too long and the names in the list do not follow a common convention. 

![caddisfly](https://user-images.githubusercontent.com/12456965/44837320-9bb14700-ac39-11e8-98bb-f32f8d777956.gif)

# Opportunity

Ensure that each test is names following a set pattern that then the Flow team can follow to create the separate cascading drop downs in the form editor. 

Define what the drop downs should be and how they should be named (select parameter, test method, etc.) in this issue: https://github.com/akvo/akvo-flow/issues/2842

**Comment by stellanl** [comment]
Maybe the list of tests should become a cascade?

**Comment by janagombitova** [comment]
That is a good suggestion @stellanl I will add the possible categories breakdown in the Flow issue. 

With this issue Nischal and Mert need to make sure that there are no odd name structures that do not follow the pattern. I noticed these 4 "parts" of the names divided by a dash: 

The naming holds these 4 categories: 
- what the testing is for: water or soil 
- what testing method is used: Sensors, Test strips, Colorimetry, Miscrobiology
- brand 
- parameter  

@nhternup can you and Mert confirm that these are indeed the categories and that all the current test follow the structure?

**Comment by nhternup** [comment]
Some suggestions for categories:

-  **Soil, Water**

- **Biological** (e.g. Bacteria, Fungi, Virus...), **Chemical** (e.g. Fluoride, Chlorine...), **Physical**: (e.g. Turbidity, Suspended solids, Moisture...)

- **Brand**

- **Parameter**

- **Liquid test** (uses a cuvette or chamber to hold the sample), **Sensor / Meter** (Electrodes, probes, measuring devices), **Strip test** (Test strips to be dipped in sample)

**Comment by MBlommestijn** [comment]
Proposed cascades:

- **Category** --> Soil/Water

- **Test type** --> Photometer/Test Strips/Sensors/Microbiology/Tester/Tube

- **Brand + Device** --> Lovibond MD610/Hanna Checker; Hach/Quantofix/Merck; Lovibond sensor/Caddisfly; Aquagenx CBT; Lovibond Tester; DelAgua tube

- **Parameter** --> e.g. Ammonia, Iron, E. coli, pH, Free Chlorine etc.

-  **Range + Unit** --> e.g. 0.1 - 8 mg/l

**Comment by MBlommestijn** [comment]
Examples:

Water - Photometers - Lovibond MD610 - Ammonia - 0.02-1 mg/l (reagent Order-No.: 517611BT)
Water - Photometers - Hanna Checker - Fluoride - 0.0 - 20 mg/l
Water - Test Strips - Hach - Nitrate; nitrite - 0-50 mg/l; 0-3 mg/l
Water - Test Strips - Quantofix - Iron - 0-100 mg/l
Water - Sensors - Lovibond SD 70 - EC - 0-1000 μS/cm
Water - Microbiology - Aquagenx CBT - E. Coli - 0-100 MPN
Water - Tester - Lovibond Tester - Iron - 0.1-2.0 mg/l, 6.8-8.2 pH
Water - Turbidity Tube - DelAgua Tube - Turbidity - 0-2000 NTU 

This is according to the following 5-level structure:
Category —> Soil/Water
Test type —> Photometer/Test Strips/Sensors/Microbiology/Tester/Tube
Brand + Device —> Lovibond MD610/Hanna Checker; Hach/Quantofix/Merck; Lovibond sensor/Caddisfly; Aquagenx CBT; Lovibond Tester; DelAgua tube
Parameter —> e.g. Ammonia, Iron, E. coli, pH, Free Chlorine etc.
Range + Unit (+ reagent ordering number if applicable) —> e.g. 0.1 - 8 mg/l (reagent Order-No.: xxxxx)

**Comment by MBlommestijn** [comment]
Adjustments:
1. Include MD610 test numbers (e.g. 60 Ammonia)
2. Include chemical formula at the end (e.g. 0.02-1 mg/l NH4) 
3. Reagent type can be left out (liquid, powder, tablet)
4. Use singular form (e.g. photometer instead of photometers)
5. Add test strip reagent no. (e.g. 91351)
6. Combine the last two levels to one level: parameter + range + unit + Chemical formula (+ if applicable Order-No)

New examples:
Water - Photometer - Lovibond MD610 - 60 Ammonia 0.02-1 mg/l NH4 (reagent Order-No.: 517611BT)
Water - Photometer - Hanna Checker - Fluoride 0.0-20 mg/l F
Water - Test Strip - Hach - Nitrate/Nitrite 0-50 mg/l NO3 / 0-3 mg/l NO2 (91351)
Water - Test Strip - Quantofix - Iron 0-100 mg/l Fe 2+ Fe 3+ (91344)
Water - Sensor - Lovibond SD 70 - Electrical Conductivity 0-1000 μS/cm EC
Water - Microbiology - Aquagenx CBT - E. Coli 0-100 MPN
Water - Tester - Lovibond Tester - Free Chlorine 0.1-3.0 mg/l Cl2, 6.8-8.2 pH
Water - Turbidity Tube - DelAgua Tube - Turbidity 0-2000 NTU

**Comment by muloem** [comment]
@nhternup can you please add an example of the new schema here so we have it as a reference. Also the new sample `xxx-tests.json` file can be deployed to one of the test instances so we can pick it up from there. 👍

**Comment by nhternup** [comment]
@muloem The feature to select a test type is available while creating the survey question only. As there is no test type selection in the app itself, there is no new schema. So the required data format/schema that would be best suited to add this feature to Flow can be specified by the Flow team.

**Comment by janagombitova** [comment]
On https://uat1.akvoflow.org/admin/ under Resources there are 2 cascades that hint how the survey editor selection could work: 

- _Caddisfly Option 1 is where the user will select category - device - parameter 
- _Caddisfly Option 2 is where the user will select category - parameter - device - range 

I prefer the 2nd option. It puts the actual testing (content) to the forefront and not the device, with which you test. Also having to select the range separatedly forces Salim to make sure he selected the right range. The only issues I see there are that we need to make it clear that there are strips that test more than one parameter (2 in 1 or 4 in 1); how to handle cases where you have total and free - are these separate parameters or do they fall under the one paramater; and is it ok that sometimes there is only one range to choose from in the end.

But I have never tested water, no nothing about this field and have no idea what the best mental models are so I wonder what you think.

**Comment by nhternup** [comment]
@muloem 
The updated tests json file is at
[caddisfly-tests.json](https://github.com/akvo/akvo-caddisfly/blob/feature/214-add-checkit/caddisfly-app/app/src/misc/caddisfly-tests.json)

**Example:**
```
   {
      "name": "Fluoride",
      "uuid": "ac6410bf-b5a3-4040-8048-ddf381223a3b",
      "sample": "Water",
      "device": "Tester",
      "brand": "Lovibond",
      "model": "CHECKIT Comparator",
      "hasImage": true,
      "results": [
        {
          "id": 1,
          "name": "Fluoride",
          "chemical": "F",
          "unit": "mg/l",
          "range": "0.2-2"
        }
      ]
    }

```

**Comment by janagombitova** [comment]
Today we discussed option 1 and 2 with Mert and concluded the following: 

**Option 1 - first test type and then parameter:** 
- from the user's point of view you define the question to test a certain parameter and the test type is just a way to test, so it does not seem intuitive to first select type and then parameter 
- we plan to add more different test types in the future resulting in this list growing longer and longer where adding more parameters is less likely as we will only add what is needed to test in the cases we support 
- this option does work better for cases where one test type measure more than 1 parameter, so the answer holds more than one value for different paramaters 

**Option 2 - first select parameter and then test type** 
- from the user's point of view it makes more sense to first select the parameter (the subject of your question) and then how you will run the test
- as we assume we will not add more parameters, this list remains shorter and thus easier to go through
- selecting the range separately in the end helps users to be sure they have selected the right test 
- this case however does not make it clear that you have selected to run a test that tests more than one paramater 

**Option 3** 
Based on the notes above we thought of a 3rd option where the user needs to decide if he will test one parameter for this question or more than one and then selects which parameter - test type - detals (range, etc). 

@nhternup, Mert and @muloem can you give it a look and let us know what you think? it is on uat1.akvoflow.org > resources > _Option 3 Caddisfly cascade

What we need to decide besides the structure is how to handle the detials as today we state: range, if it is tablet - poweder - liquid in some cases, and also a test code. Which details do we keep and which do we remove? 

![screen shot 2018-11-08 at 11 38 40](https://user-images.githubusercontent.com/12456965/48193508-e5f62900-e34a-11e8-860a-502ea6976bb3.png)

**Comment by janagombitova** [comment]
@nhternup after discussing (again) :) with Mert and Hans we decided to go for option 3. Can you check the example in the cascade in Flow and start with the prep work?

**Comment by nhternup** [comment]
A **'multiParameter'** property has been added to the json file at:
[caddisfly-tests.json](https://github.com/akvo/akvo-caddisfly/blob/feature/214-add-checkit/caddisfly-app/app/src/misc/caddisfly-tests.json#L1475)

**Example:**
```
{
      "name": "Chlorine, Hardness, Alkalinity, pH",
      "uuid": "2456d482-dbec-466c-8387-411a4093f6b6",
      "multiParameter": "true",
      "sample": "Water",
      "device": "Test Strip",
      "productCode": "2755250",
      "brand": "Hach",
      "hasImage": true,
      "results": [
        {
          "id": 1,
          "name": "Total Chlorine",
          "chemical": "Cl2",
          "unit": "mg/l",
          "range": "0-10"
        },
        {
          "id": 2,
          "name": "Free Chlorine",
          "chemical": "Cl2",
          "unit": "mg/l",
          "range": "0-10"
        },
        ...
      ]
    }
```

**Comment by janagombitova** [comment]
This issue can be closed as it will be further handled by the Flow team
