### ISSUE TITLE
Investigate using camera light with strip tests

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#206]
# Context 
Using strip tests with the app is highly dependent on the light quality when Al is doing the test. We receive a lot of feedback that checking the light quality can take quite some time and Al's patience. Sometimes the light conditions are not strong enough or there are too many shadows. 

# Opportunity 
Besides the larger UX opportunity we have here and would need to investigate, @LarsSjogreen had the idea for a quick fix without affecting the current user workflow to use the camera light when using strip tests in the app. If the camera light is on for this test type, it might give a constant stream of light and resolve the issues with shadows. 

@nhternup and @mtwestra what do you think? 

Shall we investigate and give it a try?

**Comment by mtwestra** [comment]
@janagombitova as the flash camera is in the camera, this gives unwanted shadows. So this is not a viable option. In addition, the flash light doesn't have the proper spectral composition in some cases.

Some other things we can try though: 
1) create a one-pager on how to get the light conditions right (Mert is working on this already)
2) use the Android camera API v2, which gives more control over the camera. This starts to become possible now, as the majority of phones now support this.
3) fine-tune the acceptance criteria for the test. I will be working on this.

**Comment by janagombitova** [comment]
Based on Mark's comments above and myself working on better supporting documents for doing the tests, I am closing this issue and the improvements will be handled in separate issues.
