### ISSUE TITLE
Use Android Camera API v2 to improve camera behaviour

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#209]
At the moment, the Caddisfly app uses Android Camera API v1, as this is supported by all android devices. However, this camera api also provides virtually no control over the camera.

Camera API v2 on the other hand, provides a lot more control over the camera, such as focussing at a certain distance, and linear color compensation profiles. This could make it easier for the Caddisfly strip test app to arrive at a good result, improving the user experience for users.

The Camera api v2 is available from Android 5.0 (API level 21). The market share of devices with API higher than 21 at the moment is around 90%, with probably a lower number in African countries. Therefore, an app that uses the Camera api v2 would need to detect the presence of the API, and only use the v2 when available.

**Comment by janagombitova** [comment]
@mtwestra with the change will you be making any changes to the UI?
