### ISSUE TITLE
Start button visibility

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#21]
The visibility of the button depends on the quality checks. Only if the conditions are met, the button shows. But, as long as the button is not pressed, the app keeps doing the quality checks. And, because it takes time to find the finder patterns needed to do the quality checks, and of course the checks itself, the conditions are then again not met. They are set to 'false' at the start of each cycle. The result: a start button that flickers: it's there/now it's gone. And a contrast icon that flickers: red/green.

Possible solution: make the conditions (contrast, exposure, focus) global. Then they will keep the previous value until it changes. On the downside: if quality checks fail, the previous value will still be there. So: Keep the value in a global and set to false only if failure?

**Comment by ldporsius** [comment]
The contrast icon stabilizes by use of a global. But the start button keeps switching between visible/gone if values lie around the limit set. The limit is e.g. 70%. In each call the value changes somewhat, let's say: 68%, 71%, etc. 
Maybe what we could do, is: wait a number of iterations until we can decide if values stay around the limit, or are definitely to low or high enough. 
If on the average they are above the limit, we take a chance and show the button, trusting that it will remain that way. After pressing start, the checks still keep running, so we should end up with an image of good quality. This is only to prevent confronting the user with a button that disappears while they were just about to press it.

**Comment by mtwestra** [comment]
Yes, this sounds like a good approach. But it also shouldn't last too long, so something like 3 iterations?
m

**Comment by ldporsius** [comment]
I was thinking more like 50 actually. But I'll start writing and we'll see.

**Comment by mtwestra** [comment]
Well, if it is used a source of feedback, it will only work if feedback is fast enough, otherwise people just ignore it. So it can only take one second or so.
m

**Comment by ldporsius** [comment]
Do you think so? Doesn't the camera need some more time to be sure?

It could look like this, the feedback eventually:

![device-2015-10-15-141940](https://cloud.githubusercontent.com/assets/9623423/10513459/f65a125a-7347-11e5-95dc-b8a189fd2d39.png)

**Comment by mtwestra** [comment]
I don't think the answer is popup screens. The icons should be clear enough I think
m

**Comment by ldporsius** [comment]
Do you have any suggestions what we could do after it is clear (to the app) that conditions are not likely to be going to be met? In stead of a Dialog? (popup screen you call it). In a Dialog you can change settings, so if user clicks 'No', I set the counter to zero and she can start again. How would you handle the situation without user interaction? Simply reset everything behind the screens?

**Comment by mtwestra** [comment]
I am not sure if this is needed - can't we just display the icons, as it is quite clear they change when conditions change?
m

**Comment by ldporsius** [comment]
It's not about the icons, it's about the start button. I try to get it more stable, avoid it popping in and out of view. Therefore, I came up with the solution to keep track of number of succesful quality checks. If there are enough, we show the start button. If there are not enough ... what then? Warn the user? You say: no, a Dialog is not the answer. Do not warn the user then, but just keep showing the icons. That means code-wise: reset the counter to zero. Or do I misunderstand?

**Comment by ldporsius** [comment]
Maybe we should use different names for 'exposure' and 'contrast'. Terms that are more obviously telling the user what is going on. Like 'light' and 'shadows'. I mean: 'exposure' does not mean very much to me, I think of it in terms like: 'it should nor be to dark, nor to bright'. And 'contrast' means to me: 'there musn't be a shadow'.

**Comment by mtwestra** [comment]
Yes, that is a very good idea.

Perhaps we can use 'brightness', 'shadows', 'focus'?

**Comment by ldporsius** [comment]
I'm all for it. Anyone else have any suggestions?

**Comment by mtwestra** [comment]
How about: 

1) start a counter at 0
2) when we have analysed an image and all is well, do +1 if count < 10
3) when we have analysed an image and NOT all is well, do -1 if count > 0
4) if count  > 5, show the start button

This will have the effect that we need at least 5 tests that have succeeded.

**Comment by ldporsius** [comment]
Something like that, yes. The good news is: it seems to work very well! I have just tested in the worst of circumstances, brightness just around that 70% limit, and the start button shows - and more important: it stays visible- , and the image is taken, and I get a result. 

I do not do -1, but only +1 if quality checks are true. I keep track both of the count of trues and the number of tries. If count of trues  > a preset criterium (25) => show start button. If not, and number of tries > criterium \* 1.5 => reset values (start all over).

If only five tests are sufficient, that would mean setting the criterium to 5.

**Comment by ldporsius** [comment]
If we are not actively focusing the camera, should it still be part of the criteria for showing the start button?

**Comment by ldporsius** [comment]
The whole idea of a Start button has changed. This issue has become obsolete. Closing it.
