### ISSUE TITLE
Add testing method 191 Calcium hardness MD610 Photometer

### ISSUE THREAD

**Issue by MBlommestijn** [ternup/caddisfly-app#210]
Add testing method 191 Calcium Hardness for the MD610 Photometer to the Caddisfly app.

Testing method corresponds with Lovibond reagents: 
CALCIO H No. 1 / No. 2 (Order-No.: 517761BT)
Range: 0 - 500 mf/l CaCO3

**Comment by janagombitova** [comment]
Released on 4th October 2018
