### ISSUE TITLE
Add analytics to track which tests are being used

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#211]
# Context

Add the ability to collect app and test parameter usage data.

## Data to collect

**Test Data:**
1. Test name
1. Test Id 
1. Brand name
1. Test kit type
1. Test kit model id, range

# Why

To decide whether to support or remove tests it is important to know what tests are being used by users of Akvo Caddisfly.

Currently it is not easy to create such usage reports from Flow survey data as they are spread over many instances. So either Akvo Flow app or Akvo Caddisfly could send usage data to a central place where such reports could be generated.

# Next steps

Investigate Firebase Analytics to see if we can collect the above data and create reports on what tests are being used.

# Implementation

When a test is completed in Akvo Caddisfly, the test results are sent to Akvo Flow. At the same time the data with additional info could also be sent to an analytics database (i.e. Firebase Analytics)

**Comment by janagombitova** [comment]
@nhternup all sounds good but I wonder why also capture the **Flow data**? I am not sure having that data would be helpful for us. 

Could Caddisfly just capture data regarding to which tests are being used?

**Comment by nhternup** [comment]
Description updated

**Comment by janagombitova** [comment]
@nhternup after talking with Mert about this we wondered if it would be possible to know to which Flow instance is the data being sent to (the Flow app is connected to)? Can Caddisfly app access that data?

**Comment by nhternup** [comment]
Caddisfly does not currently have access to instance information. Flow app will have to add this information to the data sent to Caddisfly on launch of a test.

**Comment by janagombitova** [comment]
@valllllll2000 Hey Valeria, we are expanding the Caddisfly app to capture simple stats on the usage of different tests. The intention is to know which tests are used the most so we can better coordinate the development work and which tests should be further added and which can be removed. Today this is tracked manually and it is a pain. 

There is one more insight that can help us also better coordinate changes with partners, and that is to know which Flow instance is actually using the tests and to what scale. What do you think of Nischal's comment above, would this be doable and would it be a large change?

**Comment by valllllll2000** [comment]
@janagombitova @nhternup Here is the current data we send to caddisfly to get a test:
https://github.com/akvo/akvo-flow-mobile/blob/develop/app/src/main/java/org/akvo/flow/ui/view/CaddisflyQuestionView.java#L159
I can easily add another field to send the instance name. Which one do you need? akvoflow-xx format or the actual name ie footballforwater? Field name could be "instanceName"? And only newly released apps will send that (olde versions will not) so you have to make sure to check if field is present until everyone updates.

**Comment by janagombitova** [comment]
@valllllll2000 that is wonderful. The actual name would be easiest, but we can also do with the akvoflow-xx. So choose the one that is least effort. Thank you

**Comment by nhternup** [comment]
**Screenshot of data collected for a test in Firebase analytics:**

![analytics](https://user-images.githubusercontent.com/4124856/47981315-615c9e00-e0f1-11e8-865b-b30b6568cd7d.PNG)

**Screenshot of count stats of tests:**

![count](https://user-images.githubusercontent.com/4124856/47988498-60833680-e108-11e8-94de-a53bab2993b0.PNG)

**Comment by janagombitova** [comment]
@valllllll2000 can you create an issue in the Flow app and push with the next release to add the instance name with the data we send to caddisfly to get a test?
