### ISSUE TITLE
Checkit (Lovibond) aka 'twirly test'

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#214]
# Context
We are looking at expanding our lists of supported tests with Lovibond's **Checkit Comparator**, http://www.lovibondwater.com/products/Environmental/visual-water-test-kits/water-analysis-comparator.aspx and here is a detialed doc on the product: http://www.lovibondwater.com/files-product/CheckIT%20Comparator.pdf

It is a compact, lightweight colorimetric unit of two plastic tubes where the water samples go and a twirly colour scale disk that then indicates the value. One Checkit tests one parameter.

<img width="762" alt="screen shot 2018-10-30 at 15 08 43" src="https://user-images.githubusercontent.com/12456965/47723870-bada4e00-dc55-11e8-8d2d-400220742c3d.png">

## Parameters
Here is the list of parameters they support.

Parameter | Range
--- | --- 
Alkalinity Total M | 20-240 mg/l CaCO3
Aluminium | 0-0.3 mg/l
Ammonia | 0-1 mg/l
Ammonia | 0-0.5 mg/l
Bromine | 0-5 mg/l
Chlorine | 0-4 mg/l
Chlorine | 0-1 mg/l
Chlorine | 0-2 mg/l
Chlorine | 0-0.3 mg/l
Chlorine Dioxide | 0.01-0.2 mg/l
Chlorine (total) | 10-300 mg/l
Chlorine (free) | 0-3.5 mg/l
Chlorine | 0-3.5 mg/l
Copper | 0-1 mg/l
Copper | 0-5 mg/l
Copper | 0-1 mg/l
Copper (free) | 0-5 mg/l
Copper (free) | 0-1 mg/l
DEHA | 0-0.5 mg/l
Fluoride | 0.2-2 mg/l
Iron | 1-10 mg/l
Iron | 0-1 mg/l
Iron TPTZ | 0.1-1.8 mg/l
Manganese | 0.1-0.7 mg/l
Manganese | 0.02-0.2 mg/l
Molybdate | 0-100 mg/l
Molybdate | 50-500 mg/l
Molybdate | 0-10 mg/l
Nitrate | 0-1 mg/l
Nitrite | 0-0.5 mg/l
Nitrite | 0-0.3 mg/l
Ozone | 0-1 mg/l
pH Value | 6.5-8.4
pH Value | 5.2-6.8
pH Value | 6-7.6
pH Value | 4-10
Phosphate | 0-80 mg/l
Phosphate | 0-4 mg/l
Phosphate | 0-2.5 mg/l
Silica | 0.25-4 mg/l
Silica | 0-100 mg/l
Silica | 0-1 mg/l
Sodium Hypochlorite | 2-18%
Sulphite | 0.5-10 mg/l
Zinc | 0-1 mg/l

# Why
The Checkit tests are affordable, sturdy, do not require any power to use, easy to use, available, simple, are purchasable also from other countries (so easy to get to project locations).

# Next steps 
- Add the tests as part of our porfolio of supported test starting with the drinking water priority parameters 
- Specify the parameter list 
- Create a user friendy UI in the app that avoids possible mistakes in inputting the test result 
- Replicate the UI and UX across the other Checkit test we will add

**Comment by mtwestra** [comment]
I've recreated the artwork and sent it to @nhternup directly by email.
For the initial parameter list, we'll ask Hans en Mert.

**Comment by janagombitova** [comment]
The shortlist of parameters to add from Hans: 
- Chlorine (free) | 0-3.5 mg/l
- Nitrate | 0-1 mg/l
- Phosphate | 0-2.5 mg/l
- Fluoride | 0.2-2 mg/l
- Iron | 0-1 mg/l

**Comment by janagombitova** [comment]
@nhternup here are the instructions for three out of the five selected tests.For Nitrate and Fluoride I have created a separate issues for as we do not have images yet. So lets start with these three and add the rest in a following iteration. 

# Chlorine
## Instructions 
The Checkit Comparator uses two cells, a coloured disc and a reagent.

**Steps**
1. Insert the coloured disk in the comparator.
2. Fill both cells to the 10ml mark. 
3. Close one cell with a lid and place it in the left-hand space of the comparator. It acts as a blank.
4. Add one DPD No1. (R)-tablet in the other cell and close it with a lid. Swirl the cell until reagent is completely dissolved. 
5. Place the second cell in the right-hand space of the comparator.
6. By rotating the disk, match the two colours against daylight, looking away from the sun.
 
## Range 
0-4mg/l

# Phosphate 
## Instructions 
The Checkit Comparator uses two cells, a coloured disc and a reagent.

**Steps**
1. Insert the coloured disk in the comparator.
2. Fill both cells to the 10ml mark. 
3. Close one cell with a lid and place it in the left-hand space of the comparator. It acts as a blank.
4. Add one Phosphate 3 Powder Pack in the other cell and close it with a lid. Swirl the cell until reagent is completely dissolved. 
5. Wait 2 minutes for complete colour reaction. 
6. Place the second cell in the right-hand space of the comparator.
7. By rotating the disk, match the two colours against daylight, looking away from the sun.

## Range 
0 - 2.5 mg/PO4

# Iron 
## Instructions 
The Checkit Comparator uses two cells, a coloured disc and a reagent.

**Steps**
1. Insert the coloured disk in the comparator.
2. Fill both cells to the 10ml mark. 
3. Close one cell with a lid and place it in the left-hand space of the comparator. It acts as a blank.
4. Add one IRON HR-tablet in the other cell. Crush the tablet and close it with a lid. Swirl the cell until reagent is completely dissolved. 
5. Wait 1 minute for complete colour reaction. 
6. Place the second cell in the right-hand space of the comparator.
7. By rotating the disk, match the two colours against daylight, looking away from the sun.

## Range 
1 - 10 mg/l Fe

# Extra questions 
- do you need more details for me to proceed? 
- do we need an image for the step when users need to wait a certain time interval? 
- As we agreed in the 1st round the use will input the value herself. Can we validate that the value falls between the provided range per test?

**Comment by nhternup** [comment]
> do you need more details...?

Maybe reagent codes/product number if they exist

> do we need an image for the step when users need to wait a certain time interval?

One option would be to append the wait sentence into the previous step and avoid another image...

> As we agreed in the 1st round the use will input the value herself. Can we validate that the value falls between the provided range per test?

Yes, can be validated

**Comment by janagombitova** [comment]
> do you need more details...?
> Maybe reagent codes/product number if they exist

- chlorine
   - product number: 146020
   - reagent code: 511310BT
- phosphate 
   - product number: 146480
   - reagent code: 535200
- iron
   - product number: 146320
   - reagent code: 515380

> do we need an image for the step when users need to wait a certain time interval?
> One option would be to append the wait sentence into the previous step and avoid another image...

Brilliant idea. Let's do that. Can you bold out then the time so it is more visible in the text? 

> As we agreed in the 1st round the use will input the value herself. Can we validate that the value falls between the provided range per test?
> Yes, can be validated

Perfect!!

**Comment by janagombitova** [comment]
Well done 👍 Ready for release
