### ISSUE TITLE
Adding more parameters for Checkit

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#219]
With the latest Caddisfly app release, we introduced 5 Checkit tests. See the list below. We have decided to support Checkit tests as they are easy to use and bring reliable results creating a great substitute for strip tests that are in the same price category, but less reliable and sometimes more complicated to use due to light conditions. 

# Opportunity
We currently support testing 26 different parameters. For some parameters you can use different tests for other there is only one option. Our goal is to support those parameters are partners are most likely to need when testing water in the field in projects around WASH and Agriculture. 

As we have created the basis to support Checkits it is an easy way to support more parameters if seen valuable. The intention of this issue is to see if there are more parameters we see valuable to add to our portfolio. 

## Parameters

Here is the list of parameters we support today: https://docs.google.com/spreadsheets/d/1lTQFCV1xTU2k9FIWrAcgnuAdU6QA3mQQ4ORRhpgW1Ds/edit#gid=0

Here is the list of parameters they support.

Parameter | Range | Added? 
--- | --- | --- 
Alkalinity Total M | 20-240 mg/l CaCO3
Aluminium | 0-0.3 mg/l |
Ammonia | 0-1 mg/l |
Ammonia | 0-0.5 mg/l |
Bromine | 0-5 mg/l |
Chlorine | 0-4 mg/l | *
Chlorine | 0-1 mg/l |
Chlorine | 0-2 mg/l |
Chlorine | 0-0.3 mg/l |
Chlorine Dioxide | 0.01-0.2 mg/l |
Chlorine (total) | 10-300 mg/l |
Chlorine (free) | 0-3.5 mg/l |
Chlorine | 0-3.5 mg/l |
Copper | 0-1 mg/l |
Copper | 0-5 mg/l |
Copper | 0-1 mg/l |
Copper (free) | 0-5 mg/l |
Copper (free) | 0-1 mg/l |
DEHA | 0-0.5 mg/l |
Fluoride | 0.2-2 mg/l | *
Iron | 1-10 mg/l | *
Iron | 0-1 mg/l |
Iron TPTZ | 0.1-1.8 mg/l |
Manganese | 0.1-0.7 mg/l |
Manganese | 0.02-0.2 mg/l |
Molybdate | 0-100 mg/l |
Molybdate | 50-500 mg/l |
Molybdate | 0-10 mg/l |
Nitrate | 0-1 mg/l | *
Nitrite | 0-0.5 mg/l |
Nitrite | 0-0.3 mg/l |
Ozone | 0-1 mg/l |
pH Value | 6.5-8.4 |
pH Value | 5.2-6.8 |
pH Value | 6-7.6 |
pH Value | 4-10 |
Phosphate | 0-80 mg/l |
Phosphate | 0-4 mg/l |
Phosphate | 0-2.5 mg/l | *
Silica | 0.25-4 mg/l |
Silica | 0-100 mg/l |
Silica | 0-1 mg/l | 
Sodium Hypochlorite | 2-18% |
Sulphite | 0.5-10 mg/l |
Zinc | 0-1 mg/l |

**Comment by janagombitova** [comment]
Mert has made a shortlist of which parameters to add and will provide all the necessary details here.

**Comment by MBlommestijn** [comment]
CHECKIT Comparator tests to add:

Alkalinity Total M | 20-240 mg/l CaC
Aluminium | 0-0.3 mg/l
Ammonia | 0-1 mg/l
Chlorine | 0-1 mg/l
Copper | 0-1 mg/l
Iron | 0-1 mg/l
Manganese | 0.1-0.7 mg/l
Nitrite | 0-0.5 mg/l
pH Value | 4-10
Phosphate | 0-4 mg/l
Phosphate | 0-80 mg/l

**Comment by janagombitova** [comment]
Released in 1.0.8
