### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by kusHELL** [ternup/caddisfly-app#220]
While building the project "import org.akvo.caddisfly.R" gives an error, as there is no such module.
![screenshot 1](https://user-images.githubusercontent.com/23027644/50446571-904a0000-093b-11e9-84e8-4600a9493996.png)

**Comment by nhternup** [comment]
Android Studio sometimes has these problems. Try the following:
1. Ensure Android Studio is the latest version. Preferably 3.2 or 3.3 and above
1. Ensure code is latest version with 'git pull' and is on 'master' branch
1. Ensure Build Variant selected is 'mainExtDebug'
1. Build -> Rebuild Project
1. Disable 'Instant Run' in Preferences
1. File -> Invalidate Caches / Restart
1. File -> Sync Project with Gradle Files

**Comment by nhternup** [comment]
Closed due to inactivity. Please reopen if problem persists
