### ISSUE TITLE
Add 3 new parameters for MD610

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#226]
A partner in West Africa asked us to support 3 new parameters: Lead (Pb), Nickel (NI) and Zinc (Zn). We will add support for these for the MD610 photometer

**Comment by MBlommestijn** [comment]
It is not possible to measure Lead (Pb) with the MD610 photometer and we have currently not found a testing method for which we do not need a laboratory.
We will add the following 3 requested parameters for the MD610 photometer:

- 150: Copper (Cu) - tablet - range: 0.05 - 5 mg/l Cu
- 257: Nickel (Ni) - tablet - range: 0.1 - 10 mg/l Ni
- 400: Zinc (Zn) - tablet - range: 0.02 - 0.9 mg/l Zn
