### ISSUE TITLE
Force larger distance for photo

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#23]
At the moment, the whole preview size is used, which means that the camara is naturaly held quite close to the calibration card during the measurement. This has a number of disadvantages:
- the phone sometimes has a hard time finding the right expose and focus 
- it is easy to cast a shadow with the camera onto the calibration card
- close by, the camera distorts the image

To remedy this, we can do the following:
- in the preview screen, only show a portion of the actual preview image. If, for example, we show only 50% of the image, this will have the effect that the user puts the camera higher so she sees the whole calibration card
- Don't select the middle of the image but rather the top middle part. This will have the effect that users move the camera away from the normal to the card towards themselves, in order to see the whole card. In this way, there is less risk for casting a shadow.

**Comment by ldporsius** [comment]
Can you maybe post a link to (a) project(s) that have implemented this? I find it hard to understand how to deal with it. I understand the purpose, but not the way to achieve it.

**Comment by ldporsius** [comment]
You say: 'show a portion' and 'select the top middle part'. How do you do that? My best guess sofar is to set the zoom of the camera to a larger value, so the user is forced to hold it at a larger distance to view the whole card. Would that work? Only my camera (Samsung Galaxy Ace III) doesn't support zoom or so it tells me.

**Comment by mtwestra** [comment]
What I would do is:
1) get the preview image
2) cut out a part (not sure if this is possible)
3) show that part

**Comment by mtwestra** [comment]
I wouldn't use the zoom for this actually, I don' think it is necessary.
m

**Comment by ldporsius** [comment]
If you 'cut out' a part, assuming that is possible, how and when are you going to show the whole image? 
Maybe we could not cut, but hide a part of the whole.

**Comment by mtwestra** [comment]
We wouldn't show the whole image ever.

The idea is that if on the preview screen you only see a part of the image, you automatically adjust so the calibration card is completely visilble in that part.
The part of the image should fill the whole preview screen, of course.

**Comment by ldporsius** [comment]
I don't understand. If you only show a part of the image, how can you adjust to see the whole?

**Comment by ldporsius** [comment]
If I only show my thumb, how can I move the camera to see my whole hand?

**Comment by ldporsius** [comment]
If I show my whole hand, but hide the area where my four fingers are, then, when I move the camera further away, larger distance, my fingers and thumb will be visible where previously only my thumb filled the screen.

**Comment by mtwestra** [comment]
for example:
1) in the phone, only show the top half of the preview image
2) put the calibraiton card on the table
3) adjust the phone so that you can see the whole calibration card on the preview screen
4) the effect that this has, is that the calibration card now fits in the top half of the 'real' preview image

**Comment by mtwestra** [comment]
by moving the camera further away

**Comment by ldporsius** [comment]
Again: do you know of any projects that have this feature?

**Comment by mtwestra** [comment]
no ...

Perhaps these are useful (found by searching for "android crop preview image")?
http://stackoverflow.com/questions/8601982/is-it-possible-to-crop-camera-preview

http://stackoverflow.com/questions/11626869/how-to-crop-image-on-camera-preview-goggles-style-android

It seems it is not direcly possible, but some solutions are proposed (in the first link):

"You could put the camera preview (SurfaceView) inside a LinearLayout that is inside a ScrollView. "

**Comment by ldporsius** [comment]
Following the first link: Hiding upper and lower part works. (the answer from 'drees') We have to decide how much we hide.

I have set it to 300dp width for now and that way I am forced to hold the camera about 40cm above the card (without 'cropping' it used to be 20cm).

![hiding_view](https://cloud.githubusercontent.com/assets/9623423/10611493/a79bfbc0-774c-11e5-938e-b923bac4164b.png)

**Comment by mtwestra** [comment]
great! so that works

**Comment by ldporsius** [comment]
Well, it is totally different than how you described it, but if the purpose is to show the whole card but only from a certain larger distance, yes, it works.

**Comment by ldporsius** [comment]
One, IMHO, reason that this doesn't work is the following:
What the camera 'sees' is different from what the user sees. It has to be for this to work, because the actual preview has to be larger than the view that shows the image, otherwise it is pointless. But, what the camera sees is what matters when  it comes to finder pattern detection and quality checks.
So: even if I still hold the device close enough to the card for the finder patterns to be found, the qualtity checks start and if all is OK, the start button appears. Therefore, this is still no guarantee absolutely that the user is forced to keep a distance from the card.

**Comment by ldporsius** [comment]
The same goes for the 'Linear Layout inside ScrollView' approach. There also the camera preview is larger than the LinearLayout size.

**Comment by mtwestra** [comment]
And now the idea is to only hide the lower part, so the user is forced to move the camera towards himself. Can we give that a try?

**Comment by mtwestra** [comment]
We can do something about this by only looking for finder patterns inside a certain area

**Comment by ldporsius** [comment]
Before we proceed to discuss the meaning of hiding a lower part, please consider my remarks on the flaws of this approach.

**Comment by mtwestra** [comment]
Did you see my comment on that one? I think we can work around that. What I am interested in is to establish if you can force the user to hold the camera off-center using this method. Could we do that experiment?

**Comment by ldporsius** [comment]
I saw your comment and we could do something like: if the finder pattern has x, y that lies within the View that user sees, it is taken into account. I suppose. 
What you really would want, I am thinking, is a hiding-algorithm that adjusts itself based on the position of the finder patterns. If I look through the camera now, what I see is a bottom black area where the view is 'cut'. Now if that area would be able to in- and decrease, we might have something that does the trick. Experiment with that I say.

**Comment by ldporsius** [comment]
We are definitely going for this approach. Closing issue.
