### ISSUE TITLE
Consistency in numbering of instructions

### ISSUE THREAD

**Issue by MBlommestijn** [ternup/caddisfly-app#240]
Currently, the numbering of instructions is sometimes absent, restarting in each following screen or is consecutive. 
For consistency, all instructions should have consecutive numbering.

Testing methods that still need consecutive numbering:
- Test strips
- MD610 photometers
- Lovibond SD sensors
- Turbidity Tube

Testing methods that already have consecutive numbering:
- Tester
- Coliform
- CHECKIT Comparator

**Comment by janagombitova** [comment]
We will add automatic numbering thus we need to ensure an instruction that is just one step is not split to more paragraphs and add a `/` where no order numbers are needed
