### ISSUE TITLE
Change e.Coli workflow

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#243]
With Mert we looked today at the user workflow for e.Coli tests and for the case where we want to add TC to e.Coli tests (issue #236). 

# Problem 
Currently when testing e.Coli in initial screen gives you two options: Next (brings you to input the data) and Instructions. The Instructions also hold details on how to input the data what is a bit confusing today. Furthermore, in the field the user workflow is a bit different as you first collect the sample, incubate the sample for at least a day and then input the data. 

# Goal 
We aim to support the actual testing workflow as best as possible. This means to show the instructions when they are relevant in the workflow and keep the workflow as simple as possible. 

# Idea 
With this issue, we want to change the workflow for the e.Coli tests. The idea is to create two workflows within the test: 
1. Prepare sample (holding the instructions and bringing you back to Flow app at the last step)
2. Submit result after incubation (holding instructions on how to input data, data input and bringing you back to Flow with the data)

# Next steps 
* [x] change initial screen to add two buttons/action items: '1. Prepare sample' and '2. Submit result after incubation'
* [x] include instructions 1 - 11 to the first step, Prepare sample, see below 
* [x] last screen of the first step should have an action button to go back to Flow app 
* [x] implement new workflow for the second step, Submit result after incubation, see below
* [x] change some instructions, see below

## Workflow for the first step 
![Caddisfly step 1](https://user-images.githubusercontent.com/12456965/62533940-2639f780-b848-11e9-8364-50d1239646c8.png)

## Workflow for the second step 
![Caddisfly step 2](https://user-images.githubusercontent.com/12456965/62534288-1373f280-b849-11e9-9fcd-5952838cdf7d.png)

## Instructions changes 
Some changes to the instructions also need to be applied: 
- Step 1: Prepare the work area and put on plastic gloves. 
- Step 11: change top incubation temperature to 35-37 degrees Celcius, time 20h

**Comment by janagombitova** [comment]
@nhternup I have only one comment in regards to the screens you sent this morning: http://caddisfly.heliohost.org/instructions/?id=ed4db0fd3386

![Screen Shot 2019-08-14 at 08 31 36](https://user-images.githubusercontent.com/12456965/63000326-28680b80-be71-11e9-99b8-bd21fad671b9.png)

Could we do two buttons, one an outlined - medium emphasis for the Preparing the sample and the second a contained - high emphasis one for Submitting the result? Can we place them next to each other with the outlined button on the right and contained one on the left? The text should be capitalised and shortened. I propose: Prepare sample, Submit result.

https://material.io/design/components/buttons.html#usage

Otherwise it looks good/

**Comment by nhternup** [comment]
In some languages the words/phrases are longer. How about a vertical arrangement:
Example below with different orders. First order probably makes better sense:

![startTestEn](https://user-images.githubusercontent.com/4124856/63035468-d2c74980-bed8-11e9-908f-7c4e9776f4f2.png)   &nbsp;  ![startTests](https://user-images.githubusercontent.com/4124856/63034517-246ed480-bed7-11e9-918b-a869ae1decb5.png)

**Comment by MBlommestijn** [comment]
Looks good, but I would place the 'Prepare sample' above the 'Submit result' button since that's the logical order.
