### ISSUE TITLE
Update Spanish translations

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#244]
As part of making the app useful in more countries we want to improve the transaltions of the app. This time Spanish

**Comment by valllllll2000** [comment]
@janagombitova I can't get access to the app strings on transifex to make the translations, can someone give me access?

**Comment by janagombitova** [comment]
@valllllll2000 My bad, I forgot. You should have an invite in your inbox now.

**Comment by valllllll2000** [comment]
- [x] Spanish translations completed on transifex
- [ ] Pull translations to use them in the app

**Comment by nhternup** [comment]
Thanks @valllllll2000, transifex has been updated with some strings that were missed.

**Comment by valllllll2000** [comment]
@nhternup in order for me to translate, would it be possible to see the screenshots? It would really help to see where the string is used as some are a bit tricky
