### ISSUE TITLE
Support in-app updates

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#245]
We often see the our users do not update their app version. We are not sure why. It can be because 'it feels like too much hassle' to update the app, or they are on a low data bundle. But each app update brings our users benefits, so the idea is to make updating the app version as easy as possible. 

@nhternup shared this that we would like to implement in the app: https://developer.android.com/guide/app-bundle/in-app-updates

**Comment by nhternup** [comment]
| **Update Notification**  | **Update Downloaded** |
| ------------- | ------------- |
| ![app-update](https://user-images.githubusercontent.com/4124856/69505181-7b605d00-0f4e-11ea-9770-a628f705f363.png) | ![update-ready](https://user-images.githubusercontent.com/4124856/69505182-7b605d00-0f4e-11ea-87df-15a53c1e53f3.png) |
