### ISSUE TITLE
New nickel test for MD610

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#256]
Nickel 
- Old reagent is not available anymore
- Need to add another test under the MD610 portfolio
- Mert to provide an update of the instructions as well as the images 

https://www.lovibond.com/ix_pim_assets/Wasseranalytik/BookOfMethods_Publication/Einzelmethode/M256/Instruction_Manual_Single_Method_-_M256_-_Nickel_L_-_en.pdf

**Comment by janagombitova** [comment]
Mert to provide: 
* instruction images 
* add the test to the list  
* instruction text

All details: https://docs.google.com/spreadsheets/d/18MKanQHpX590RA93yKY9McEwd74aJiuVihm5VZgzeCA/edit?usp=drive_web&ouid=108143009609136989573

**Comment by valllllll2000** [comment]
Images are here https://drive.google.com/drive/u/1/folders/1C0l8g8E9QUm7DjurZdeLeXuHSrbidkAN
