### ISSUE TITLE
Experimental setup for testing strip test method quality

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#26]
We need an experimental procedure for determining the quality of the strip test measuring method. Basically, we need to establish that this method of 'reading' as strip test is at least as good as the manual method of judging the colour by eye.

To do this, @bjelkeman suggests to do a proper double-blind research setup, which could take the following shape:

1) prepare 10 different concentrations of the fluid under investigation, in the relevant range. 

2) get two groups of 10 students.  One group will only do the manual tests, the other will only do the caddisfly strip test.

3) let the students in each group test the 10 solutions, either with the manual strip test, or with the caddisfly app. For each student, use a different random order of the test tubes, to avoid measurement bias. 

4) compare the results of both groups in terms of accuracy (closeness to true result) and precision (spread or standard deviation of measurements)

An adaptation will be needed to measure the difference between different light conditions, ie. inside/outside.

It would be good if the end result is a scientific paper.

**Comment by ldporsius** [comment]
The app will certainly gain credibility by this, especially if we can find students prepared to publish there outcomes in a paper.
