### ISSUE TITLE
Adapt HACH 5-in-1 strip test timers 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#269]
A partner reported that they noticed differences between the timers on the Caddisfly app and the instructions provided by the manufacturer for the HACH 5-in-1 test. After desk research and contacting HACH we could not confirm our assumption that the strip tests have been changed, what means we made a mistake at implementation. 

The reported difference: 
* Hach: for the second part of this test, the bottle says to dip the strip for 30 seconds, then immediately take a reading. 
* Caddisfly: directions explain to dip the strip for 30 seconds, dry off excess water, and then there is a 30-second countdown before a reading is taken.

We need to update the instructions and take the reading immediately (remove the 30-second reading countdown)

**Comment by janagombitova** [comment]
I believe it is this test: 2755250 | Chlorine, Hardness, Alkalinity, pH from our overview file https://docs.google.com/spreadsheets/d/18MKanQHpX590RA93yKY9McEwd74aJiuVihm5VZgzeCA/edit#gid=528445046

**Comment by janagombitova** [comment]
From what I understand in stage 2 we need to remove the instruction `to dry off excess water` and remove the `30s timer` to do the reading right away

**Comment by valllllll2000** [comment]
This test contains 2 stages:
Stage 1 is total hardnes, total alkalinity, ph
Stage 2 is Total chlorine and free chlorine

they are defined here:
![Screenshot from 2020-11-12 12-54-09](https://user-images.githubusercontent.com/923280/98940212-f2d62600-24ea-11eb-8139-deeebad0b83e.png)

Stage one will stay the same but stage 2 has the following modifications
* remove the instructions to dry off excess water
* remove timers (set them to 0)

Here are the changes with before (left) and after (right)

<img src="https://user-images.githubusercontent.com/923280/98942380-2fefe780-24ee-11eb-8804-b0c3a6d6676c.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/98941982-9aecee80-24ed-11eb-902c-d8eb57cccb73.png" width="200" />


<img src="https://user-images.githubusercontent.com/923280/98942378-2ebeba80-24ee-11eb-8692-c3cb546fafc2.png" width="200" /><img src="https://user-images.githubusercontent.com/923280/98941984-9c1e1b80-24ed-11eb-89c6-a3440d25115d.png" width="200" />

**Comment by janagombitova** [comment]
Looks good to me
