### ISSUE TITLE
Change to portrait view of calibration card

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#27]
When using landscape mode with the full preview, the risk is that a shadow is cast by the phone and hands. Instead, we can use the portrait view, and only show the top 1/3 of the preview screen. This has the effect that:
1) the user rises the camera to fit the whole calibration card in the image
2) the user moves the camera back towards himself, to fit the image.

**Comment by mtwestra** [comment]
@ldporsius , this perhaps also means that the 'perform test' button could move down, so it is easier to reach when you hold the phone in one hand

**Comment by ldporsius** [comment]
Do you mean the 'start' button?

**Comment by mtwestra** [comment]
@ldporsius, I meant the 'perform test' button on the screen before the preview screen, but what I really meant is that it would be good if all buttons can be used by your thumb when you hold the phone, so both the 'perform test' one, and the 'start' button

**Comment by ldporsius** [comment]
We could do a second round of mockups, inviting Loic to join in, until we have something to our satisfaction.

**Comment by ldporsius** [comment]
We could also study Maurice Ravel's concerto for the left hand:

https://www.youtube.com/watch?v=KJTUUKAdZDU

:)

**Comment by mtwestra** [comment]
I think we could first try it out, and see if it works as we expect, and then ask Loïc to adapt the mockups to the new portrait layout.

**Comment by mtwestra** [comment]
always a good option :-)

**Comment by ldporsius** [comment]
Created branch strip-test-portrait-mode.

**Comment by ldporsius** [comment]
It seems that something goes wrong in rotating the strip since we implemented this. I know that it goes wrong, but could this be the cause? A couple of tests (10) indicate that when the camera is hold at an angle, the strip is not detected properly. We need to debug this ASAP.
