### ISSUE TITLE
Use 'level' quality parameter

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#28]
to make sure the calibration card image is straight enough, we can use a 'level' quality parameter.

![6pcs-12-7mm-spirit-font-b-level-b-font-font-b-round-b-font-font-b](https://cloud.githubusercontent.com/assets/478954/10616012/3f360b90-7763-11e5-9e66-1bf05c08234a.jpg)

Alternatively, we could show a 'level' indicator with an arrow: the arrow shown is the direction in which the user needs to move the camera.

The arrow to show can be determined by looking at the relative distances of the finder patterns. If the camera is held at an angle, the 'nearby' finder patterns will have a larger distance between them. From this, the location of the camera, and the needed adjustment, can be calculated.

**Comment by ldporsius** [comment]
Another approach could be, take the atan2 from the triangle formed by the vector that is the difference between x and y of two finder patterns.

https://en.wikipedia.org/wiki/Atan2

E.g. We take the top-right and top-left patterns.
float x = topRightX - topLeftX;
float y = topRightY - topLeftY;
float angle = Math.atan2(y, x);

(angle is between pi and -pi, but we do Math.toDegrees(angle) to get a value between 0 and -90)

If angle == 0 (or -90?), the patterns are in a straight line, if angle == 90 , well that is impossible, but anything larger than 1 degree means that you are not holding the camera as you ought to.

We do the same for bottom-left and top-left. Both angles should be approx. zero, than it is OK.

**Comment by ldporsius** [comment]
What is the best way to visualise this? 
I tried to draw circles on a canvas, so that 0 degrees results in a circle right in the middle of the canvas, and + or - a degree results in a circle above or below (or left/right) of the center. A bit like the image above, where I see a centered circle and another one that is a bit off-center.

**Comment by mtwestra** [comment]
I actually think that showing a circle is fine, but i would also show arrows to show which way the user should move to

**Comment by mtwestra** [comment]
I don’t understand why this would work?

**Comment by ldporsius** [comment]
![level](https://cloud.githubusercontent.com/assets/9623423/10789565/7b552da6-7d7e-11e5-8910-76026273ec98.png)

How do you feel about a rotating arrow, like a compass?

**Comment by mtwestra** [comment]
It can’t be only rotating, because if I move it from the top to the bottom, I don’t want the arrow to move through the horizontal position to get there. In addition, when the leveling is good enough, the arrow should not be there at all

**Comment by ldporsius** [comment]
What do you mean by 'it'? 'It' can't be rotating, if I move 'it'?

**Comment by mtwestra** [comment]
I mean, an image consisting of a rotating arrow doesn’t do what we want. For example, if I start with having the phone tilted towards me, then I want to see an arrow that points away from me. If I then move in that direction, the arrow stays pointing in the same direction, until it is level enough, and then the arrow should disappear. If I move further, I want to see an arrow pointing towards me. In that sense, I think an arrow that can point in 4 directions is enough.

**Comment by ldporsius** [comment]
![device-2015-10-28-164425](https://cloud.githubusercontent.com/assets/9623423/10793959/57950426-7d93-11e5-9bde-8c74f44a48f5.png)

![device-2015-10-28-164446](https://cloud.githubusercontent.com/assets/9623423/10793971/64b2d0f2-7d93-11e5-9dbc-28108d8b07fd.png)

![device-2015-10-28-164500](https://cloud.githubusercontent.com/assets/9623423/10793987/6ddc6c74-7d93-11e5-95cc-a7da336c22ab.png)

![device-2015-10-28-164513](https://cloud.githubusercontent.com/assets/9623423/10793999/76033680-7d93-11e5-967d-fd23c6de920e.png)

**Comment by mtwestra** [comment]
Yes, exactly!

**Comment by ldporsius** [comment]
The arrow is not rotating as a compass needle does, it is more static, only switching between four directions. It merely indicates what the user should do, not the exact position of the camera.

**Comment by mtwestra** [comment]
Perfect, I misunderstood. The images you send look great.

**Comment by ldporsius** [comment]
You'll have to see it working to judge if it works...but sofar it seems like a good beginning. It does add to the project, I believe, for when I think I am holding the device straight enough, this level indicator thinks otherwise, and so it helps to get a better image. It is however very, very subtle, the difference I mean. Nothing a warp cannot handle.

**Comment by mtwestra** [comment]
If it is too subtle, then you can relax the quality parameter there to accept small deviations.

**Comment by ldporsius** [comment]
No, I mean: the deviations are never more than 10 degrees max. And for that you really have to do your best.

**Comment by ldporsius** [comment]
Should level still play a role in determining if the start button shows?

**Comment by mtwestra** [comment]
Yes, I think so. But we should be pretty lenient: +/ 10 degrees or so is no problem. But when the arrows show, we shouldn’t show the start button

**Comment by ldporsius** [comment]
Closing.
