### ISSUE TITLE
Limit internal storage of images

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#29]
We should not store an image for each patch if there is no time-lapse between the readings.

To realise this, we could keep a list of the combination image/patch-number, e.g.
{
[0,0],
[0,1],
[1,2]
}

This means: first and second patch share the same image, third patch has another image.

**Comment by ldporsius** [comment]
In view of the fact that we are now doing all of the data transfer from Activity to Activity through internal storage, I would like to bring this under your attention again.
Do we need to build in a check if internal storage has enough room?
Where and when can we safely delete data from it?

**Comment by nhternup** [comment]
Currently no impact on the storage has been noticed as the files generated are temporary. Will reopen if new info comes to light about this.
