### ISSUE TITLE
Introduce three-step workflow for measurement

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#32]
Given the fact that the light conditions are very important for a good quality measurement, we will introduce a three-step measurement process. The work flow will become;

1) a screen showing two buttons: 'prepare test', and 'instructions'
2) When a user selects 'prepare test', a screen is shown with the image preview and the quality checks. This allows the user to check if the light conditions are ok for a measurement, and to adjust her position to find the right light conditions. When the app decides the quality checks are passed, a button is shown 'next'.
3) the next screen contains the instructions to a) do the actual test, i.e. insert the strip test in the water, b) to put the strip in the black square, and c) to press 'start measurement'
4) after 'start measurement' is clicked, we show the screen showing the preview, the quality checks, and the list of actions: start, picture 1, picture 2, ... analyse.
5) when the final stage of analysis is completed, we show the results.

**Comment by ldporsius** [comment]
De instructies zoals getoond na het klikken op de 'Next' button.
Alles komt uit strips.json, behalve de " - " voor de tekst.
Er is de mogelijkheid om tekst in rood te schrijven: in de strips.json 
zet je die tekst tussen <!> en <!
Maar misschien kan dat handiger?

Hoe lijkt het zo? Ik zal nog kijken naar de vinkjes en dan maak ik weer 
eens een video.

Linda

**Comment by mtwestra** [comment]
Ik zie geen plaatje?

**Comment by ldporsius** [comment]
![device-2015-11-20-104403](https://cloud.githubusercontent.com/assets/9623423/11297120/9956a082-8f76-11e5-9797-64ebb602c731.png)

**Comment by ldporsius** [comment]
The instructions come from strips.json. There you can choose to mark text as 'important'. You put '<!>' and '<!' (without quotes) around the piece you think should be red.

**Comment by ldporsius** [comment]
'READY' can be 'START MEASUREMENT' or just plain 'START'.

**Comment by mtwestra** [comment]
’Start’ is fine I think

**Comment by ldporsius** [comment]
Showing quality checks feedback in CameraStartTestFragment: 
![device-2015-11-25-151200](https://cloud.githubusercontent.com/assets/9623423/11399331/ebaabf8a-9386-11e5-9cd5-96bf99a688da.png)

**Comment by ldporsius** [comment]
This seems to cause no further problems. Feedback from third party confirms it is an asset. Closing.
