### ISSUE TITLE
Autofocus of camera on different devices has strange behaviour

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#39]
Devices tested on:
- Samsung
  - Galaxy Ace
  - Galaxy Neo
  - Galaxy SII 
- Motorola
  - XT1039

**Description of behaviour**
On the Samsung devices the camera focuses without programmatically giving the command.
On the Motorola device sometimes the focus is correct, sometimes it does not focus at all.
And if finder patterns are all four detected, Motorola seems to go into a continuous focus.

**Comment by ldporsius** [comment]
I can boil it down to what happens in the setFocusArea method in BaseCameraView.

> mCamera.cancelAutoFocus();
> Camera.Parameters parameters = mCamera.getParameters();
> parameters.setFocusAreas(subAreas);
> mCamera.setParameters(parameters);

It all goes well, without any exception thrown, but this last line:

> mCamera.setParameters(parameters);

seems to cause the Motorola device to focus actively (or auto focus)

**Comment by mtwestra** [comment]
@ldporsius, On a HTC device, the focussing didn't happen at all, as far as I could tell. I don't know the reason though.

**Comment by ldporsius** [comment]
> Applications should call autoFocus(AutoFocusCallback) to start the focus if focus mode is FOCUS_MODE_AUTO or FOCUS_MODE_MACRO.

http://developer.android.com/intl/ja/reference/android/hardware/Camera.Parameters.html#getFocusAreas%28%29

It is surprising that the Samsung devices do focus without this call?
@mtwestra The code you tested on the HTC (was it during the meeting at TU Delft?) did not have a call to Camera.autofocus(AutoFocusCallback).
Recent code has however, in an attempt to solve that problem.

**Comment by ldporsius** [comment]
I now call Camera.autofocus(AutoFocusCallback) in a Runnable that posts itself. Started at the beginning of CameraActivity instance. The docs are not very clear if a one time call makes sure the autofocus mechanism is set to work, or if you must call it every time you need a focus.

**Comment by ldporsius** [comment]
The time lapse between the autofocus I set to 5 secs. That way it will not cause the preview to zoom in-and-out to much, because that makes it unpleasant to look at. If the camera does have a decent focus, it is not in the way, if it doesn't, well you have to wait a while, but at least you get a second round.

**Comment by mtwestra** [comment]
Sounds good

**Comment by ldporsius** [comment]
I cannot think of a reason why Camera.setParameters(parameters) would cause the device to focus?
Except that there must be a link between the auto-focus setting and one of the parameters being focusAreas. You don't have the HTC with you @mtwestra ? I only have the one Motorola that shows this behaviour.

**Comment by mtwestra** [comment]
@ldporsius, I don’t have a HTC, but there might be one in the Akvo office somewhere. I’ll ask around

**Comment by ldporsius** [comment]
I searched the www, but could not find anything useful. For practical purposes, if we are not able to fix it, in my opinion it works well without setting focus areas. Maybe it is better to concentrate at the camera focussing. I find it does so with this recent addition.
I propose: I will commit the code commenting out the setFocusAreas.

**Comment by ldporsius** [comment]
@mtwestra : It would be good to be able to test on the HTC or any other device!

**Comment by mtwestra** [comment]
@ldporsius, yes, I agree on not focussing on the focus areas. :-)

**Comment by ldporsius** [comment]
Closing.
