### ISSUE TITLE
2.1 Recognise calibration card using QR code finder patterns

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#4]
We will use QR-code style finder patterns to locate the information on the calibration cards. 

There are three finder patterns: top left, top right, and bottom left.

The code should be able to:
1) from a preview image, locate the finder patterns
2) do this as fast as possible, so the patter finder code needs to be optimised for the known size of the finder patterns, and the known relative distances of the patterns
3) to this reliably, so the code should only accept the 3 patterns if they are the 'right way up'

The code should deliver the coordinates of the three finder patterns, and the estimated module size, so it can be used as a coordinate system for the whole image.

One question is how we should make the coordinate system: should we use the centers of the modules as the zero point, or one of the corners? If we do corners (for example, always the top left corner of the pattern), it will be easier to align when we create the calibration cards themselves.

The coordinate system of the calibration card will be defined with the (0,0) point in the top left corner.

**Comment by ldporsius** [comment]
Apart from 3. the code should only accept the 3 patterns if they are the 'right way up', I think we covered this in the app. 
I now make an new bitmap with the boundingbox from topleft x,y to topright x,y and down to bottomleft x,y. Those values are returned by the 'centers' of the found patterns. I adjust for the 'estimated module size' to leave out the patterns in the result image.

So I think we should look into zxing code to find out how we can built in the check if the patterns are the right way up.

**Comment by mtwestra** [comment]
Yes, indeed.

**Comment by ldporsius** [comment]
![device-2015-07-09-145737](https://cloud.githubusercontent.com/assets/9623423/8595936/a9997570-264c-11e5-9daa-f79023e1d8da.png)

**Comment by mtwestra** [comment]
Looks good. Now we also have enough white space around the whole thing to use for calibration / shadow checking.

**Comment by ldporsius** [comment]
Yes I could pick up the work on shadow from here. I was thinking, if we want to base color detection upon the exact knowledge of where the colors are, all white space around them should be of the same size. Like this:
![device-2015-07-09-151004](https://cloud.githubusercontent.com/assets/9623423/8596046/3ed9982c-264d-11e5-9834-f26a024c296e.png)

**Comment by ldporsius** [comment]
Now it is not precise, but would that be something to take into account in our final design?

**Comment by ldporsius** [comment]
Or should the first column on the left be half the size? You know what I mean; so that each square has the same amount of white space around it.

**Comment by mtwestra** [comment]
Yes, absolutely. In fact, if you look carefully, you will see that the distance between the color patches is the same as the distance to the bottom corner of the finder pattern. 

But we can use the centers of the finder patterns our (0,0) and (0,1) points.

**Comment by ldporsius** [comment]
Indeed. The distance seems a bit larger but that can be an optical trick. It could be a question of how the result image is scaled inside the ImageView. I'll look into that.

**Comment by ldporsius** [comment]
It looks better already if I set scaletype to 'centerInside' in the imageView. 
What I log is:

I/System.out﹕ ***warp_rotate_dst w,h: 800, 480 ratio: 1.6666666666666667 type: CV_8UC4

So that tells you that the size of the result image after the warp is still the same as the size of the preview image. (also that it is now an 8 bits four channel type)

**Comment by mtwestra** [comment]
This works fine now, closing issue
