### ISSUE TITLE
User interface as regarding quality checks II

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#42]
**Description of problem**

Sometimes the quality checks quickly turn out valid, you get let's say 3 out of 5 in rapid succession.
Then they seem to 'hang', while the indicators show that there is no problem.

**Comment by ldporsius** [comment]
**Suggestion for debugging**

Because the checks happen as often as multiple times per second, logging values in the logcat is not a very efficient way of getting to the cause of this problem. There are just to many entries.
What we could do, is keep track of the checks in a HashMap, like we do for the version number read from the bar code (issue #19). 
That would give us a Map with three entries: shadowOK, brightnessOK, levelOK and the number of times they were found to be OK.
Reading the HashMap will give concise information which of the checks is blocking the lot.

**Comment by mtwestra** [comment]
@ldporsius, but how will you read the hashmap during operation? Another options perhaps could be to display it on the screen of the device?

**Comment by ldporsius** [comment]
**Suggestion for debugging II**

What also may be a cause of this problem, is to much strain on the Main Thread. Although it is updated in the background of an AsyncTask, still all the updating of the finder patterns and the quality check views is (of course) done on the main UI. 
One tool to use is the Memory log available in Android Studio, and I have been for a while looking at it while this process runs. Only the memory log shows no great outliers as far as I have seen.

**Comment by ldporsius** [comment]
> Another options perhaps could be to display it on the screen of the device?

Yes, I was thinking about that. Just for debugging purposes, but it must not put extra strain on the main UI. View above.

**Comment by ldporsius** [comment]
> how will you read the hashmap during operation?

Just let the logcat write the entries in it, I suppose. We do the same for version number. Or did, that may be outcommented.

**Comment by ldporsius** [comment]
I always use System.out.println().

**Comment by ldporsius** [comment]
Today I wrote some that doesn't help the strain on the main UI, I'm afraid (issue #39)
I should first take care that focusing the camera is on a separate thread. Maybe even tell that thread that is has no priority? But the problem existed before that.

**Comment by ldporsius** [comment]
Thinking about it, how could it be that main UI stress causes the blocking of the process? It really cannot be so. Because we count the number of OK's separately from updating the views, right? So: even though the main UI might have to much to do, that would not prevent the code to go to the next step: showing the start button if number of checksOK > 5.
And that does not happen. So it must be a problem with the quality checks itself. I think.

**Comment by mtwestra** [comment]
@ldporsius, hence the need for logging what is going on with the quality checks…

**Comment by ldporsius** [comment]
I can let the qualityCheck method return an int[] that contains [1, 1, 1] if all OK, and every other possible combination. Then not only add 1 or 0 to 'countQuality', but split into countShadow, etc. Then if all the counts `>` 5 , start button shows. 
Logging on screen will then show the values of all three.

**Comment by ldporsius** [comment]
**witnessed behavior**
The debug view (that shows the counts for Brightness, Shadows and Level) shows the following:
- sometimes shadow count = 0 (zero) while shadow indicator is all green (two green dots at end)
- shadows and level keep on counting, even when camera is flat on table

**Comment by ldporsius** [comment]
**witnessed behavior**
The level count freezes and holds things up.

**Comment by ldporsius** [comment]
**level count freezes and holds things up**
Because the criterium is set to : the **sum** of the angles must be smaller than ... X
X must be double the value of the criterium for one angle.

So: X == 2 \* Constant.MAX_LEVEL_DIFF

**Comment by nhternup** [comment]
Quality checks will now timeout with appropriate message if it takes too long
See https://github.com/akvo/akvo-caddisfly/issues/79
