### ISSUE TITLE
Second test has brandname of previous one (wrong values for patches)

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#43]
After returning from the ResultActivity and starting a new test, with a different brand, the previous value for brandname is still the one passed to the intent that starts the CameraActivity.

**Comment by ldporsius** [comment]
I removed flag 'no-history' for ChooseStripTestDetailActivity from the manifest. I moved the code fetching the brandname (id) from the onCreate() to the onCreateView() in ChooseStripTestDetailFragment. The brandname is now correct every time you start a new test, also after using the redo-button in ResultActivity.

**Comment by mtwestra** [comment]
Is this committed to strip-test yet? Should I use this version?

**Comment by ldporsius** [comment]
Not committed yet. The temporary fix seems to 'work'. Although this last one seems more to point.
Or I could commit into a branch 'stable-bug-fixes' ?

**Comment by ldporsius** [comment]
Second time round, bug reappears. Sorry, I spoke to hastily.

**Comment by ldporsius** [comment]
**public static final int FLAG_ACTIVITY_CLEAR_TOP = 0x04000000;**
- If set, and the activity being launched is already running in the
  - current task, then instead of launching a new instance of that activity,
  - all of the other activities on top of it will be closed and this Intent
  - will be delivered to the (now on top) old activity as a new Intent.
    *

**Comment by ldporsius** [comment]
**steps taken**
- set FLAG_ACTIVITY_CLEAR_TOP in Intent that starts up DetailActivity
- in DetailActivity move getting brandname from onCreate() to onResume()

_(I would imagine that onNewIntent(Intent intent) would get called, but it doesn't)_

**Comment by ldporsius** [comment]
Fixed
