### ISSUE TITLE
Create strip image to be returned to FLOW

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#48]
After a strip test is completed, the results need to be forwarded to FLOW, so they can be synchronised with a central database. The data returned should include the interpreted results for each patch, some metadata such as calibration quality and timestamp, and the actual (calibrated) strip image for each patch, including the colour swatches used. In short, for each patch we need to create an image such as this:

![stripresult](https://cloud.githubusercontent.com/assets/478954/11808173/1345290c-a31f-11e5-9dd4-35e0aeae4dd0.png)

This images includes the following:
1) the calibrated strip image
2) the swatches as defined in the JSON file
3) a circle of the interpreted colour, together with the interpolated value
4) a supporting line to clarify the meaning of the circle.

Technically, this can be accomplished as follows:

1) create a new Mat object (in Lab) to hold the image
2) put the strip image in the Mat object
3) create squares for the patches with the right Lab patch colours, as identified in the JSON file
4) using the putText function of openCV, add the text of the values (http://docs.opencv.org/java/2.4.2/org/opencv/core/Core.html#putText(org.opencv.core.Mat, java.lang.String, org.opencv.core.Point, int, double, org.opencv.core.Scalar))
5) put the line and circle with the interpolated text.
6) transform the whole image to an RGB bitmap.

**Comment by ldporsius** [comment]
Steps taken sofar:
- in ResultActivity: create a JSONArray (array)
- for each patch: create a JSONObject (object)
- put in object the following
  - "name", description of patch e.g. 'Chlorine total'
  - "value", value
  - "unit", unit
  - "img", base64-encoded string of image data, image being the same as shown on screen.
- put object into array
- put array.toString into extra's of intent that is send back to FLOW

Referencing issue #51

**Comment by ldporsius** [comment]
https://cloud.githubusercontent.com/assets/478954/11808173/1345290c-a31f-11e5-9dd4-35e0aeae4dd0.png

**Comment by ldporsius** [comment]
![device-2016-01-18-170817](https://cloud.githubusercontent.com/assets/9623423/12396148/323c8146-be06-11e5-81d6-95adab8b39b2.png)

**Comment by ldporsius** [comment]
Above the first attempt to make an image as in the draft the issue starts with.
FONT_HERSHEY_SIMPLEX and FONT_HERSHEY_COMPLEX used. I do not like them much, because they are not very easy to read. Are there extra options to improve that?

Do we want to position the circle more accurately, or is this good enough?

_The colors of the strip patches are not true for Chlorine; they are artificial_
_The second circle, the one at the bottom, is not part of the Bitmap (that is meant to be send back in a json array to FLOW). That is a custom view living inside Android only._

**Comment by ldporsius** [comment]
Do we want to show this image in ResultActivity, or is it meant to only send it back to FLOW?

**Comment by mtwestra** [comment]
Only to send it back to FLOW

**Comment by mtwestra** [comment]
This is the original sketch?

**Comment by ldporsius** [comment]
Here is how it looks now:

![warp23](https://cloud.githubusercontent.com/assets/9623423/12457120/2f52e896-bfa3-11e5-8c11-87eeb3940ba7.png)

**Comment by mtwestra** [comment]
Perfect
