### ISSUE TITLE
Suggested improvements after user testing

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#50]
After user testing at the TU Delft, the following improvements were suggested:
1) make the black area a bit larger, so it is easier to put the strip on it
2) add quality check to see if the strip crosses the boundary of the black area
3) add quality check to see if the strip has been put the wrong way around
4) at the bottom of the strip, add an area with a simple illustration of how the strip test should be placed - i.e. with the strips to the left.
5) don't do any extrapolation

**Comment by mtwestra** [comment]
In addition:
6) see if we can ditch the opencv code, to save on space. The openCV manager download is already 10MB, and then it needs to download more code.

**Comment by arthurakvo** [comment]
Update:
-We don't need opencv manager anymore. 
-Illustrating the placement of the strip on the card is something we urgently need to consider.

**Comment by janagombitova** [comment]
No longer relevant
