### ISSUE TITLE
Integration with caddisfly app

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#51]
Make strip test project ready for integration with main app.

**Comment by ldporsius** [comment]
Integration branch is called 'develop-integration-strip'. It was branched from 'develop'.

**Comment by ldporsius** [comment]
http://stackoverflow.com/questions/3105673/how-to-kill-an-application-with-all-its-activities

In order to be able to return to the survey after submitting results, I have done the following:
- create a class BaseActivity that holds a static property for a listener (interface) and the interface itself.
- in BaseActivity a setter for listener.
- in ColorimetryStripActivity, set this listener to 'this' (the ColorimetryStripActivity)
- ColorimetryStripActivity implements BaseActivity.Listener
- ResultActivity extends BaseActivity and therefore has access to listener.
- in ResultActivity when button 'save' is clicked, the listener method 'onResult()' is called.
- this calls ColorimetryStripActivity to finish with the intent passed, which intent holds the result data.
- this calls ExternalActionActivity onActivityResult(...) method.

To get the app to go to ExternalActionActivity, I followed the tips in the SO-article linked to above, by means of starting each activity following it with '...forResult' and in each activity override onActivityResult to check if resultcode == 0 (must change that to proper variable). If true: finish().

**Comment by mtwestra** [comment]
Sounds much like magic to me. it works beautifully!

**Comment by ldporsius** [comment]
The approach as described does not work. It was a mere coïncidence, the resultcode 0 being the same as when the Intent is not holding any data.

**Comment by ldporsius** [comment]
In a standard scenario, the flow is as follows:
A -> startActivityForResult -> B -> calculate result -> setResult("OK", result) -> finish

Our scenario is more like:
A -> B -> C-> D

where D is the ResultActivity that calculates result,
and result must go back to A

**Comment by ldporsius** [comment]
For C and D, we set a Flag 'FLAG_ACTIVITY_CLEAR_TOP', because we need to make sure that the Intent is delivered with its new Extras (brandname). Otherwise it seems that the old Intent prevails. 

This should lead to C and D being only one instance at the top of the stack when instantiated.
We do not do this for B.
Now when in D, and we have our result, and we want to go back to A, I thought, we could make a new Intent, put result in Extras, set the flag to 'CLEAR_TOP', and start A with that intent. I would expect that B, C and D would finish and A started holding these Extras.

**Comment by ldporsius** [comment]
A does start and holds the Extras. But D is not finished unless I call finish() upon it in D itself.
If I call finish() upon A, I get B at the top.

**Comment by ldporsius** [comment]
And more important: the intent that starts A, holding the Extra's, does not deliver them to FLOW Activity, let's call that Z (for Zero), when finish() is called. 
In Z, the onActivityResult(int request, int result, Intent data) contains an empty Intent. 
request is still the one originally started with, but result is 0 (should be -1).

**Comment by ldporsius** [comment]
In case B get's on top (visible on screen) and using the back button, then Z does get the right intent back.

**Comment by ldporsius** [comment]
For a fix that seems to work, stressing 'seems', I took this steps:
- set flag in Manifest for B to 'noHistory'.
- use a listener to set the result data String in the intent of A.
- finish() when listener method is called
- extra finish() when returning from D to A with an Extra called 'finish'

I am quite at a loss here, but my best guess is, that it has to do with the original Intent, that mustn't be overwritten. I hope to come to a real understanding of this, any help will be greatly appreciated.

**Comment by mtwestra** [comment]
How does Nischal handle it in the rest of the Caddisfly code?

**Comment by ldporsius** [comment]
Speaking for Nischal: it starts in ExternalActionActivity. Method: startTest().
There depending on an ENUM, a liquid or strip test Activity is started, started forResult, with an intent that holds requestCode set to REQUEST_TEST.

**Comment by ldporsius** [comment]
Then, e.g. the SelectDilutionActivity is started. That extends BaseActivity, the same as ExternalActionActivity.
There the method  startTest() is invoked, again that start an ActivityForResult, the AlignmentActivity.
SelectDilutionActivity also holds an override of onActivityResult(...) 

 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

```
    switch (requestCode) {
        case REQUEST_TEST:
            if (resultCode == Activity.RESULT_OK) {
                Intent intent = new Intent(data);
                this.setResult(Activity.RESULT_OK, intent);
            }
            finish();
            break;
        default:
    }
}
```

**Comment by ldporsius** [comment]
Well, this is just going to be to much, going through all of the code here.

**Comment by ldporsius** [comment]
Data is collected and send back. Closing.
