### ISSUE TITLE
Consider adding M3 Ecoli petrifilm plates

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#52]
Ecoli  can be detected by M3 petrifilm plates, which are filled with 1 mL of fluid, and then incubated for 24 hours. We could create image recognition to count the ecoli plates automatically. This would also have the usual benefits of having the data, the image, and the interpretation in a database automatically.

Examples: 
- http://opencfu.sourceforge.net/
- http://www.cellprofiler.org/
- http://www.the-scientist.com/?articles.view/articleNo/35281/title/Down-for-the-Count/
- http://imagej.nih.gov/ij/index.html

**Comment by nhternup** [comment]
Will be added to roadmap if needed
