### ISSUE TITLE
Create json file in assets that holds instructions in french language

### ISSUE THREAD

**Issue by ldporsius** [ternup/caddisfly-app#58]
To be able to present to the user instructions (in step two of the strip test workflow, and in the instructions activity) in a language other than the default (English), we need to make them available in assets.
We do not want them to be part of the json that holds generic data for the strip test, such as color information, for that conflicts with any updates of those, whereas instructions may remain the same.
(We do not want to have to update all strips-[locale].json with every new print of a calibration card)

We therefore could create a separate file, that has a property 'brand' in common with the generic file, and besides that has a property 'instructions' that holds the information in the language of choice. The property 'brand' is also used as an identifier for the images stored in assets/images/striptest.

In code, to read back the instructions in the preferred locale, we read back from res/values-[locale]/strings.xml what the path to assets/strips-instructions-[locale].json is.

**Comment by mtwestra** [comment]
Yes, good idea

**Comment by ldporsius** [comment]
Done.
