### ISSUE TITLE
2.3 Correct the perspective of the captured image

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#6]
Before we use the image to extract the color values and the strip, we need to correct the perspective. As we will use the position of the finder patterns to define a coordinate grid, we need the grid to be straight.

To do this we can do:
1) determine the position of the finder patterns
2) use the positions to define a quadrilateral transform
3) apply the transform to the image, rendering a straightened image.

**Comment by ldporsius** [comment]
I think you would like to look into what OpenCV can do with correcting the perspective. It is very interesting.

http://docs.opencv.org/modules/core/doc/operations_on_arrays.html?highlight=perspective#cv2.perspectiveTransform

**Comment by ldporsius** [comment]
http://docs.opencv.org/doc/tutorials/features2d/feature_homography/feature_homography.html#feature-homography

This tutorial shows how you can detect a known image in your camera image. It combines Homography and PerspectiveTransform. It looks good to me; you can see in the example that you can detect a rectangle that corresponds to the image you want it to match with.  I am not sure how this can be of use to us, but I think it would be worthwhile to look into the PerspectiveTransform.

**Comment by ldporsius** [comment]
'As we will use the position of the finder patterns to define a coordinate grid'

I think that it is'nt necessarily so, using OpenCV. Sorry to contradict. We might first use zxing library to find our FindernPatterns, but we can give our-selves more room, still. I mean, first we focused upon QR-code reading. We discovered that we really had no benefit from that. It worked better to learn from what they are actually doing, understand that, and so we where able to implement it in a way we want, namely, find only the patterns at the edges and from than go on.

Now, having OpenCV to out disposition, I would really like the opportunity to discover that library, if you call it a library that is. It is good to know that we already covered the zxing FindernPatterns, we can always return to that, but if I can make things more simple still using OpenCV, I would very much like to work that out. It won't take months, only a couple of days.

**Comment by mtwestra** [comment]
I think we should use the simpelest tools, once that we understand well, to do what we want to accomplish. Image processing libraries act as a black box, which might sometimes give unexpected results. So using the finder patterns is still a good idea I think, because it gives us an easy way to know where everything is in the image.

On the other hand, it is a good idea to explore what openCV can do.

**Comment by ldporsius** [comment]
![device-2015-07-09-121541](https://cloud.githubusercontent.com/assets/9623423/8593019/57505404-2634-11e5-91db-b7f24ac3088f.png)

Using opencv and the position of the finder patterns.
http://docs.opencv.org/doc/tutorials/imgproc/imgtrans/warp_affine/warp_affine.html

**Comment by ldporsius** [comment]
Now the image is extremely blurry, but we have another issue for that, I believe.
Also another issue: it is now 'cut out' at the centers of the finder patterns. Since in this design those are placed below the edges of the color areas, not all is visible. 
We could do:
- place the patterns with the centers aligned with the top/bottom of where the information lies
- enlarge the area by adding the 'estimated module size' (the size of the black/white lines inside the finder patterns)
  I do not know which is the more reliable. I think the first might be. _Estimated_ module size: the word says enough.

**Comment by mtwestra** [comment]
I can make some new versions with the alignment you propose.

**Comment by ldporsius** [comment]
How do the stickers you ordered look?

**Comment by mtwestra** [comment]
Like this:

![sticker](https://cloud.githubusercontent.com/assets/478954/8595741/fc4a9d64-264a-11e5-87f4-cfebc53a3b08.jpg)

**Comment by ldporsius** [comment]
? I don't see...

**Comment by ldporsius** [comment]
Theoratically it is possible to find the findern patterns under an extreme angle and you get an image like this:
![device-2015-07-09-163343](https://cloud.githubusercontent.com/assets/9623423/8597982/a7f25e92-2658-11e5-96db-05e9d060198e.png)

To this I have already applied a warp and a rotation. You can see that top left and right and bottom left are reasonably well adjusted, but we have no way of knowing where bottom right is. Or do we?

**Comment by ldporsius** [comment]
But I really don't see people trying to take a picture while lying lazily on their sofa waving their camera randomly around, right? I simply do not expect to get images like this from users.

**Comment by ldporsius** [comment]
If we add a findern pattern in the bottom right corner, zxing is going to take that into account and you get a rotated image. You could rotate that back I suppose, but than still you only have three coordinates. 
We could try and detect the edge between white and black in the bottom right part?

**Comment by mtwestra** [comment]
we could add a 4th finder pattern, and then use a perspective transform.
The edge detection would also work, but then we make it dependent on an item in the image that might change. I think it is a nice philosophical idea to let the only the finder patterns determine the location and orientation.

**Comment by ldporsius** [comment]
I thought I'll give it a try  and now we can detect four patterns in an image. I just changed some 3's int 4's...it wasn't hard.

**Comment by ldporsius** [comment]
first test shows that image get's rotated. so we still need to implement a way to define _our_ top left.

**Comment by ldporsius** [comment]
Based on four findern patterns and a perspective transform, we get this:

![device-2015-07-22-163001](https://cloud.githubusercontent.com/assets/9623423/8827835/2d147318-308f-11e5-9bad-63f345c51d90.png)

The original image I cannot show here, but it was taken under an angle. So the transform is doing it's job. It does seem to me that the upper and bottom lines are somewhat curved, don't you agree? Or is that my interpretation?

**Comment by ldporsius** [comment]
Some examples of this perspective transform:

http://www.pyimagesearch.com/2014/08/25/4-point-opencv-getperspective-transform-example/

http://ramsrigoutham.com/2014/06/14/perspective-projection-with-homography-opencv/

**Comment by mtwestra** [comment]
This works fine now, closing issue
