### ISSUE TITLE
2.4 Check illumination quality of captured image

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#7]
We need to check if the global illumination level of the image is acceptable, because we don't want to adapt it before doing the calibration. This means both checking the global illumination level,and the if the illumination is homogenous across the image.

To do this, we need to determine a way to measure the global illumination level, This could be done as follows:

1) in a grayscale image, there should only be some limited percentage of pixels with the extreme values, so 0 and 255. We need to determine a good cut off value for this. If pixels have these extreme values, it means that they are either under exposed, or over exposed, and in both cases information is lost.

2) for the R, G, and B channels, this should also be checked, in order to check oversaturation

3) For the grayscale image, we should find some additional quality check to see if the histogram of values is as we want it. For this, we might want to look at the histogram for a few 'good' and 'bad' images, and see what we can learn from that.

To determine if the illumination is homogenous accross the image, one option to use is to look at a few horizontal and vertical white lines of which we know the location. For each of these lines, we could say that the individual values of all the pixels on the line should not differ more than some small percentage (3% - 5%?) from the average value of all the pixels on the line. This will detect if there are local differences in the illumination.

**Comment by ldporsius** [comment]
Yes, indeed, a very good idea. Today I started working upon that. I try to detect the white in the image by using a threshold. If we now where 'white' is, than we can average the value of 'white', use that as our threshold, and do some calculation of wherein the white the shadow lays. What OpenCV offers is that you can detect areas (squares/boundingbox if you like, or the precise shape of the area found).

So I think we could do this :
- detect white
- within the white, detect the difference between very bright and not bright.
- if the difference is to high, reject image

Of course I need to see this working first. Only getting started with OpenCV.
@mtwestra  Do you have an algorithm that you think does the trick?

**Comment by ldporsius** [comment]
Image is partially shaded. A red line is drawn around the area that is 'white' enough.

![device-2015-07-05-092248](https://cloud.githubusercontent.com/assets/9623423/8510724/a3d61cb8-22f7-11e5-9167-f46a5d22ce18.png)

**Comment by ldporsius** [comment]
Moved the image out of the shade.

![device-2015-07-05-092323](https://cloud.githubusercontent.com/assets/9623423/8510731/e1ae6bf8-22f7-11e5-915a-843e931d3aae.png)

**Comment by ldporsius** [comment]
Maybe we could use this, if we look for finder patters within the area (within the red lines). That guarantees that they are not found in an image that is not bright enough, or partially shaded. What do you think?

**Comment by mtwestra** [comment]
I would probably take a slightly different approach, based on the fact that we know where the white should be.

The process could be:

this should already have been done:
1) find finder patterns
2) check overall exposure

Then to test for shadows, you can do:
1) select a few lines of white, that cover the extend of the image. For example, the lines between the finder patterns (with an imaginary 4th finder pattern location computed from the three others). We know these should be white.
2) compute the average value of pixels on those lines
3) iterate over all the pixels in the lines again, and check that no pixel deviates by more than, say, 5% of the average value.

Any shadows present should easily be detectable in that way.

**Comment by ldporsius** [comment]
http://www.ijcsi.org/papers/IJCSI-10-4-2-270-273.pdf

I came across the article above and found it very interesting. So I tried to implement what it says, which is not easy because I really know very little mathematics, but I did get a result:

![device-2015-09-10-123205](https://cloud.githubusercontent.com/assets/9623423/9791407/351f6be4-57db-11e5-8327-80ceae3c873b.png)

The blue line was drawn around the shadows.
Could it be worthwhile to explore further?

**Comment by ldporsius** [comment]
https://en.wikipedia.org/wiki/Relative_luminance

This you may find of interest also. I tried to work with a Lab schema, but I do not fully understand 
"a perceptual scale of the brightness as a nonlinear function of the relative luminance Y."

**Comment by mtwestra** [comment]
The main problem I see here is that this method will probably work for very clear shadows, but that we need to detect very subtle shadows as well. The method I proposed handles that.
 m

**Comment by mtwestra** [comment]
indeed interesting. But I think the problem here might be that this method will work well with very clear shadows, but we also have to notice subtle shadows. The method I proposed originally can do that. Perhaps we can also look at that method?

m

**Comment by ldporsius** [comment]
When we try to determine shadows by looking at a few white lines, we need to know where those lines are. Currently, we moved the code of perspective transform away from CameraPreview to a separate Activity. So we could implement it, but not in the process of quality checks during the finder-pattern-find cyclus. We could replace the current shadow detection code with the approach you suggest.

**Comment by mtwestra** [comment]
The information of where the white lines are is embedded in the JSON file of the calibration card. The function createWhitePointList in the calibration card class uses this information to sample the white areas. Indeed, we need to do the perspective transform before that.

m

**Comment by ldporsius** [comment]
@mtwestra Sorry Mark, I overrode your last commit on this one, because the debugger kept complaining about the redundancy of the construction. I suggest, that if needed for development purposes, you alter the return statement into 'return true' and comment the 'return focus && exposure && contrast'. If that's ok.

**Comment by mtwestra** [comment]
@ldporsius, I was thinking, given the result of our experiments, we can take a much simpler approach:

1) don't use the light sensor
2) from the cut out finder patterns, determine both the minimum luminosity value and the maximum luminosity value. The difference needs to be at least larger than some number. In that way, we ensure that range of luminosities is sufficient, which is really the only thing we are interested in.

The reason the light sensor is not really useful is that it doesn't say anything about the luminosity range of the captured image: it can be light outside, but the camera can still use a low exposure. The actual range of luminosities is a much better indicator.

**Comment by ldporsius** [comment]
@mtwestra I see what you mean: The exposure of the camera is the important thing here, not the value of the lux measured by a light sensor.

The way you describe: taking the diff between min and max values, I use now in the shadow detection method also. So I will do the same in the exposure method.

**Comment by mtwestra** [comment]
@ldporsius,
excellent.

**Comment by mtwestra** [comment]
handled in #11
