### ISSUE TITLE
Allow for multiple images to be returned with result

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#70]
The JSON image key format could be an array to allow for multiple images to be returned with result.

**Comment by mtwestra** [comment]
This means we will forward the following structures to the FLOW app:

In the intent, the image property will be an array of paths to images, in which the strings are escaped:
["\/storage\/emulated\/0\/Akvo Caddisfly\/result-images\/7416c217-b2b5-4670-8626-628dd16c2f05.png"]

In the answer, the image property is an array of image names:
{"result":[{"name":"Total Chlorine (ppm)","value":10,"unit":"ppm","id":1},{"name":"Free Chlorine (ppm)","value":0.5,"unit":"ppm","id":2}],"type":"caddisfly","name":"Chlorine and Free Chlorine","uuid":"bf1c19c0-9788-4e26-999e-1b5c6ca28111","image":["5a59a588-056b-4750-99bb-fd655c7105bb.png"]}

**Comment by mtwestra** [comment]
We will handle this later.

**Comment by nhternup** [comment]
Not implementing as feature not required
