### ISSUE TITLE
Support for 5 in 1 strips

### ISSUE THREAD

**Issue by abhilash1in** [ternup/caddisfly-app#71]
Please add support for measuring water quality on the Android app from 5 in 1 test strips
http://www.hach.com/5-in-1-water-quality-test-strips/product?id=7640211609

**Comment by abhilash1in** [comment]
Any updates? What are the new features in the latest commit?

**Comment by nhternup** [comment]
@abhilash1in, the release notes are available at https://github.com/akvo/akvo-caddisfly/releases/tag/v1.0.0-beta.8.5

**Comment by abhilash1in** [comment]
Thanks!

**Comment by abhilash1in** [comment]
Can I please have your email ID? It's regarding one of the existing Android app developments on the water quality test for the same 5 in 1 strip

**Comment by nhternup** [comment]
abhilash1in, I've sent you an email. Thanks for fixing image.
