### ISSUE TITLE
Start button can be pressed accidentally on pressing Next button

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#75]
During strip test, after the quality check, if the user accidentally taps the Next button more than once then the Start button on the next screen can get pressed and the instructions screen will be skipped.

Suggestion would be to remove the Next button and automatically show the instructions screen after quality check with a 'success' message above the list of instructions.

**Comment by mtwestra** [comment]
@nternup, Agreed, let’s try that
