### ISSUE TITLE
Old EC implementation not supported 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#76]
During testing the latests Flow - Caddisfly implementation I was making sure we still support the “old” caddisfly EC measurement. 

The "old" Caddisfly implmentation works via  a special flag on the free text question type and it opens the external source. Now when I want to run that test I get a “Cannot start test - Requested test is not available. Please contact technical support." 

As we have many partners who use the EC meters are the are implemented today and will not move anytime soon to the new implementation (we need to solve issues around API, supporting them in the transit, communication, etc) we need the "old" implementation to still be available. 

The test was done on version 1.0.0 Beta 3

**Comment by nhternup** [comment]
Issue moved to https://github.com/akvo/akvo-flow/issues/1808
