### ISSUE TITLE
Add soil EC and soil moisture sensors

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#80]
Add ability to use two new soil sensors : Soil EC (SEC) sensor and soil moisture (SOM) sensor.

More info: https://github.com/akvo/akvo-flow/issues/1863

**Comment by janagombitova** [comment]
@nhternup Here are the toast messages I got when plugging in the sensors:

- WaterEC406
- Soil Moisture 0
- Soil EC 361

**Comment by janagombitova** [comment]
works as expected 👍 

I did have a funny thing - the sensors were not recognized the first time and I needed to restart the phone and then it all worked. I could not reproduce the issue on another one, but I just wanted to note it down for future reference. 

Besides the above mentioned mystery all works as it should
