### ISSUE TITLE
Improve feedback to user when checking light quality - red arrow 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#83]
@nhternup I really like the information you give to the users when checking the light quality before a test starts - the blue text field informing the user what is currently happening while she is holding the phone above the colour card. 

One other information given to the user is a little red arrow in a circle that should indicate the user to move the phone in a certain way for better results. I was curious about 2 things: 
1. Have you heard feedback about this? Do users understand what they are to do? 
1. Have you considered removing the arrow and telling the user specifically what to do in the current blue text field? As now there are too many items on the screen she needs to read and pay attention to

![screenshot_2017-01-16-16-46-46](https://cloud.githubusercontent.com/assets/12456965/21981014/c900fbae-dbe5-11e6-9f8b-85ffcde12684.jpg)

By the way I really like the countdown timer you added once the tests are running. Great improvement!

**Comment by arthurakvo** [comment]
We will look in better tilt instructions, maybe even a short animation on the screen that shows the actual tilting.
