### ISSUE TITLE
Improve feedback to user when wrong sensor is connected 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#84]
Currently we have 2 different sensors the user connects to the app and all three have their specific test type. The validation (is the proper sensor connected when running a particular test) works fine. With this issue we can aim to find a better way to tell the user that he has the wrong sensor connected for the particular test he wants to run

**Current steps taken:**
1. user has EC sensor connected 
1. user selected question measuring soil moisture in Flow app
1. Caddisfly app is opened on the Soil Moisture screen
1. It appears as if the test is running 
1. Flow app is opened back on the surveys and the user sees a toast telling him to connect Soil Moisture sensor 

Can we find a better way to show the users that they need to connect the sensor? The toast disappears after a few seconds and the user might have not noticed it. Secondly, he needs to select Go To Test again to open the Caddisfly app. Perhaps we can keep him in there?

**Comment by nhternup** [comment]
![incorrect-device](https://cloud.githubusercontent.com/assets/4124856/22590530/9e773606-ea35-11e6-9146-2e5d167cff85.png)

Notification has been changed to an alert dialog. This also waits for the user to either change the sensor or cancel and go back to the survey.
