### ISSUE TITLE
Count down timer - user instructions 

### ISSUE THREAD

**Issue by janagombitova** [ternup/caddisfly-app#85]
![screenshot_2017-01-16-18-16-40](https://cloud.githubusercontent.com/assets/12456965/21983632/84c06292-dbf2-11e6-9ca6-f17b5062f76a.jpg)

When measuring phosphate there is quite a long time when the camera screen is black and the user is Waiting for phosphate. I personally did not know if I need to hold the phone still above the colour card or not due to the black screen. Does the user have to keep the phone above the card or can he place the phone down? It can be helpful to add this instruction to the Waiting for phosphate info.

**Comment by nhternup** [comment]
The phone can be set aside during the black screen. Yes probably a better message could highlight this.

**Comment by nhternup** [comment]
![waiting-msg](https://cloud.githubusercontent.com/assets/4124856/22590223/2198f1d4-ea34-11e6-928f-6ec82c20da60.png)

As there isn't enough space below the preview area for a full sentence, one option is to pop a snackbar at the bottom. This will popup only when the preview goes blank.
