### ISSUE TITLE
2.6 From the image, extract the calibration swatches and their colours

### ISSUE THREAD

**Issue by mtwestra** [ternup/caddisfly-app#9]
We need to extract the calibration colour patches from the calibration card. We can do this using the known location of the colour patches. One option is to follow this procedure:
1) get the location of the finder patterns, and from that determine the local coordination system
2) iterate over the colour patches, and take a circular sample in the middle of each patch
3) for each sample, determine the most common colour value, and put that in an array.

We should check what is the best way of defining the colour of a patch. In the Qpcard 201 that we might use, sometimes there are small white specs, and we want to ignore those. By using the 'most common colour' instead of the average, this is ok. But there might be other ways.

**Comment by ldporsius** [comment]
I visualised the area's in the calibration strip that are used to determine the color. Here is the result.
I used the x and y from the patch (the center) minus d/2 for top-left and plus d/2 for bottom-right.
- @param img Image.
- @param pt1 Vertex of the rectangle.
- @param pt2 Vertex of the rectangle opposite to <code>pt1</code>.
- @param color Rectangle color or brightness (grayscale image).

![device-2015-07-28-110113](https://cloud.githubusercontent.com/assets/9623423/8927482/0880151a-3518-11e5-996a-12a63575949a.png)

**Comment by mtwestra** [comment]
Could you include the image?

**Comment by mtwestra** [comment]
I think the P_DIST needs to be adapted a bit. 

Could you try 
P_DIST = 2.13
P_SIZE = 9.9

Or play with the values a bit until they are outlined ok?

**Comment by ldporsius** [comment]
P_DIST = 2.13
 P_SIZE = 9.9

![device-2015-07-28-122707](https://cloud.githubusercontent.com/assets/9623423/8929212/fe6d5392-3523-11e5-90d4-f5e6c802d417.png)

**Comment by ldporsius** [comment]
On the left a view of the colors of the patches. Much to dark I think. What could cause that? 
Hope it helps developing further.

**Comment by mtwestra** [comment]
The P_SIZE could be a bit smaller, perhaps 9.8. In that case, the P_DIST needs to be 2.23. 

You could go further in defining the colours by first computing the average, and then only accepting those pixels that are within a certain distance from this average. In python, I did it like this:

def dist(b1,g1,r1,b2,g2,r2):
    return math.sqrt((b1-b2)**2 + (g1-g2)**2 + (r1-r2)**2)

def measureSquare(img,bitDepth,x,y):
    totalB = totalG = totalR = 0
    totalNum = 0
    if bitDepth == 8:
        fac = 1.0
    else: 
        fac = 1.0 / 256

```
for j in range (-10,10):
    for jj in range(-10,10):
        totalB = totalB + img[y+j,x+jj,0] * fac
        totalG = totalG + img[y+j,x+jj,1] * fac
        totalR = totalR + img[y+j,x+jj,2] * fac
        totalNum = totalNum + 1

avgB = 1.0 * totalB / totalNum
avgG = 1.0 * totalG / totalNum
avgR = 1.0 * totalR / totalNum

totalB = totalG = totalR = 0
totalNum = 0
for j in range (-10,10):
    for jj in range(-10,10):
        if dist(img[y+j,x+jj,0] * fac,img[y+j,x+jj,1] * fac,img[y+j,x+jj,2] * fac,avgB,avgG,avgR) < 10: 
            totalB = totalB + img[y+j,x+jj,0] * fac
            totalG = totalG + img[y+j,x+jj,1] * fac
            totalR = totalR + img[y+j,x+jj,2] * fac
            totalNum = totalNum + 1

avgB = 1.0 * totalB / totalNum
avgG = 1.0 * totalG / totalNum
avgR = 1.0 * totalR / totalNum

return avgB, avgG, avgR
```

You can optimise by not using dist = sqrt(...), but just use dist2 = (...), so you don't do the square root. You then also need to adapt the limit of what you accept.

**Comment by mtwestra** [comment]
The calibration will take care of the darkness.

**Comment by mtwestra** [comment]
Done in #11
