### ISSUE TITLE
Multiplication factor for soil strip test results

### ISSUE THREAD

**Issue by nhternup** [ternup/caddisfly-app#93]
For soil tests the samples are diluted with water during the extraction process. Due to this the result has to be multiplied by 5 times to get the true result of the nutrients. The app therefore needs to know that a soil test is being conducted.

One way would be to have separate questions for soil tests in Akvo Flow survey. Something like this:

pH - Soil test
Available Nitrogen - Soil test
Available Phosphorous - Soil test
Available Potassium - Soil test

These tests would still use the same test strips that are being used for testing water samples but the result would be multiplied by 5 instead (except for pH)

There are also three other possible requirements for expressing soil test results:

1. Soil is usually tested for NPK (Nitrogen,Phosphorous, Potassium). Since we are using Nitrate/Nitrite and Phosphate tests, it would be better to convert and display them as Nitrogen and Phosphorous values. This uses other conversion factors for the calculation.

2. Soil test results are usually expressed as “Kilogram per hectare”. So the result would need to be further converted from ppm to kg/ha.  This again uses other conversion factors for the calculation.

3. We've noticed that the same pH strips slightly misreads the pH values when testing in soil extracts as against water. We could compensate for this variation just for soil tests to increase the accuracy of the test.

**Comment by janagombitova** [comment]
If I understand properly, on Flow side we would then have pH, Nitrogen, Phosphorus and Potassium twice (once for water and once for soil) for the user to choose from. Correct? 

If so, I think it is easier (from the user perspective) if the user defines in the beginning if he is going to run a water quality test or soil quality test and then select which parameter he wants to investigate. This would bring us to two Akvo Caddisfly question types: 
- Akvo Caddisfly Water tests 
- Akvo Caddsifly Soil tests

Each of the question types should then open up the dropdown with the list of tests (ordered alphabetically) that fall under the particular category.

As far as I know, when it comes to selling Caddisfly we will also be pricing it based on two modules: water quality tests and soil quality tests - so this implementation will also follow the same pattern. 

@nhternup and @muloem what do you think?

**Comment by nhternup** [comment]
@janagombitova, yes correct, currently those tests will show up twice. Yes would probably be good if the user is able filter the test types by category (soil, water, etc.)

**Comment by janagombitova** [comment]
Based on the discussion we just had with @nhternup and @muloem we will as the **1st implementation** have all tests shown to the user in one dropdown ordered alphabetically. The tests will be distinguished by specifying if it is a `water test` or a `soil test`. We will use a prefix to distinguish the soil tests from water tests. In some cases this will result in having a parameter in the list multiple times. The same naming convention will be used across all places. 

Secondly we agreed to remove the Phosphate HACH test as we do not want to support this strip test type considering the quality of results.
